### ISSUE TITLE
add multiple device should cache login info in memory

### ISSUE THREAD

**Issue by wuwentao** [wuwentao/midea_ac_lan#103]
### Device type and model (or SN)

none

### The description of new feature

in this chanages:
https://github.com/wuwentao/midea_ac_lan/commit/1f56e69b7ebcabdf634a8eb14c44f44dec4470e7
we have removed write username/password to local json file, and not save username/password in local disk.

it caused a small issue: 
if user have more than 5-10+ device to be add, they should add each device and input login username/password every time.
we can cache it in memory and not write to file, can be done in future

**Comment by chemelli74** [comment]
I investigate with the core Team and this is not allowed at the time writing.

**Comment by wuwentao** [comment]
> I investigate with the core Team and this is not allowed at the time writing.

understand, username/password is sensitive data, HA core may not allow to cache it.
we can delay it, not a urgent requirement.
