### ISSUE TITLE
Please add support for Midea MFP-120i

### ISSUE THREAD

**Issue by dev-inside** [wuwentao/midea_ac_lan#160]
### Device type and model (or SN)

Fan 560000AG (0)

### The description of new feature

Hi,
Just found this repo, after I've got no answer on the original one.

I'd purchased my new Fan with built in Purifier and so far, it works partly in Hassio, but the feature set is pretty limited. At the moment, HA with this integration only supports the following endpoints:

**(✅ = supported, ❌ = should be removed, ❓ = missing)**

- [x] ✅ Power on (with the Device name as switch - maybe a duplicate)
- [x] ❓ Child Lock (don't know if it works)
- [x] ✅ Oscillate (Switch)
- [ ]  ❌ Oscillation Angle (not supported - should be removed)
- [ ]  ❌ Oscillation Mode (not supported  - should be removed)
- [x] ✅ Power (Switch - this might be the real state)
- [ ]  ❌ Tilting Angle (not supported, cause the Fan doesn't tilt  - should be removed)
- [x]  ✅ Preset Modes 
  - [x]  ✅ **Normal** (Supported)
  - [ ]  ❌ _Natural_ 
  - [x]  ✅ **Sleep** (Supported)
  - [ ]  ❌ _Comfort_ 
  - [ ]  ❌ _Silent_
  - [ ]  ❌ _Baby_ 
  - [ ]  ❌ _Induction_ 
  - [ ]  ❌ _Circulation_ 
  - [ ]  ❌ _Strong_ 
  - [ ]  ❌ _Soft_ 
  - [ ]  ❌ _Customize_ 
  - [ ]  ❌ _Warm_
  - [x]  ✅ **Smart** (Supported)
  - [ ] ❓ One mode is missing: it might be called _Ionic_ or something.
- [ ] ❓ Percentage (Strength of the Ventilation aka "percentage_step" or "speed_count") => must be set to 10% (default is 33%)

### Missing entities
-  [ ] ❓ Temperature [sensor, celsius/fahrenheit]
-  [ ] ❓ Filter Status (Purifier, 2 Filters) [sensor, number/percentage]
-  [ ] ❓Timer (Set timer) [slider or input, HH:MM:SS]
-  [ ] ❓Remaining Time [sensor, number/time]
-  [ ] ❓Turn Display on/off [switch]

I hope those infos where helpful and thank you for your amazing work so far!

**Comment by dev-inside** [comment]
So, I digged a little into the topic and figured out, that there is some support for the following things in HA:

I was able to set the currently supported preset_modes via configuration.yaml

(Currently) working modes
homeassistant:
    customize:
        fan.[MIDEA-DEVICE_ID]_fan:
            preset_modes:
              - Normal
              - Sleep
              - Smart
One mode, exclusive to that model is missing. I don't know the english wording, but it would translate from German to English to something like "Ion" or "Ionic".

Fan speed
The "percantage_step" has to be set via "speed_count" in the "customize" field of the integration to the following:

{ "speed_count": 10}
The fan has in the Normal and Smart modes 10 Speeds and in Sleep only 3.

Conclusion
Overall, I guess this device might need an own category, cause it has partly features of the "fan" and the "purifier" device.

**Comment by dev-inside** [comment]
So, I digged a little into the topic and figured out, that there is some support for the following things in HA:

I was able to set the currently supported preset_modes via _configuration.yaml_


### (Currently) working modes
```
homeassistant:
    customize:
        fan.[MIDEA-DEVICE_ID]_fan:
            preset_modes:
              - Normal
              - Sleep
              - Smart
```

One mode, exclusive to that model is missing. I don't know the english wording, but it would translate from German to English to something like "Ion" or "Ionic".

### Fan speed
The "percantage_step" has to be set via "speed_count" in the "customize" field of the integration to the following:
```
{ "speed_count": 10}
```

The fan has in the **Normal** and **Smart** modes 10 Speeds and in **Sleep** only 3.

### Conclusion
Overall, I guess this device might need an own category, cause it has partly features of the "fan" and the "purifier" device.

**Comment by rokam** [comment]
Hi @dev-inside ,

The issue is that currently the lib only opens interface for every feature of a 0xFA device (aka fan). We should retrieve its capabilities to limit the preset options and show what only matters, but we need to implement something similar to what was done for 0xAC recently.
If you can, help us at https://github.com/rokam/midea-local

**Comment by rokam** [comment]
I'll fix this issue; another could be open on the lib side.
