### ISSUE TITLE
求更新小天鹅809洗衣机

### ISSUE THREAD

**Issue by 954485679** [wuwentao/midea_ac_lan#17]
### 设备类型及型号 (或SN)

0000DB5133812787441196xxxxxxxxxx

### 新功能的描述

现有的集成会提示无法连接指定设备，洗衣机型号是TG100UTEC

现在在列表中能看到该设备，且显示支持连接。美的美居中可以看到实时状态以及控制。求集成支持该设备的状态更新

**Comment by lyfqdl** [comment]
我的TD100UTEC搜索指定IP可以发现并添加，希望能增加用电量和用水量实体

**Comment by 954485679** [comment]
> 我的TD100UTEC搜索指定IP可以发现并添加，希望能增加用电量和用水量实体

我使用指定ip可以发现不能添加，能请教下怎么添加的吗

**Comment by wuwentao** [comment]
@954485679 

请按照首页readme开启debug log，重启HA，然后添加设备，出错以后，将debug log上传上来，看看报错的地方在哪里。

**Comment by wuwentao** [comment]
@954485679 收到消息以后请尽快试试，升级目前最新的v0.5.0版本，然后安装首页说明，开启midea_ac_lan和midealocal的debug log，重启HA，然后尝试添加设备，然后请帮忙上传一个debug log，方便后续对比小天鹅洗衣机无法添加的数据对比和分析吧。

**Comment by chemelli74** [comment]
1 month without any feedback.will close the issue if there will be no reply in 2 weeks

**Comment by wuwentao** [comment]
由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 https://github.com/wuwentao/midea_ac_lan/issues/275 来跟踪和处理，避免大量重复问题的跟踪和处理。
当然，当前issue仍然可以继续更新和发送其他消息
