### ISSUE TITLE
HA Thermostat Temp Incrementation Steps are wrong for my AC Unit

### ISSUE THREAD

**Issue by Xeyrruken** [wuwentao/midea_ac_lan#177]
### HA core version

2024.6.4

### Integration version

Current Latest update(new device error fix)

### Device type and model

Air Conditioner 00000Q13 (-84)

### Used App

Nethome Plus

### The description of problem

Im having an issue with Thermostat Card on HA, the temp incrementation is by .5 making it hard to change temp needing to be increased two to three time to only change a whole number, as per research apparently the issue is not the card as the steps for temp raise is by default 1.  I was wondering if there is any place on which i could change the temp increase and decrease steps to be a whole 1.

![image](https://github.com/wuwentao/midea_ac_lan/assets/12901093/46b24690-1204-4a89-a4b7-d01cc87312d9)

**Comment by chemelli74** [comment]
Hi, you need to use customize your device as per documentation.

**Comment by Xeyrruken** [comment]
> Hi, you need to use customize your device as per documentation.

Can you provide a little bit more of guidance, where exactly should i put the customization?

**Comment by wuwentao** [comment]
> > Hi, you need to use customize your device as per documentation.
> 
> Can you provide a little bit more of guidance, where exactly should i put the customization?

there is detail usage document in curren repo, you can check it from README document, click into your device type document.
for example , AC device can be found at 
https://github.com/wuwentao/midea_ac_lan/blob/master/doc/AC.md

it has example for this requirement.
just copy and paste it to your device configure setting.
