### ISSUE TITLE
我在hacs中添加这个的时候 提示如下入错 求大佬指导下 如何处理

### ISSUE THREAD

**Issue by jonny77** [wuwentao/midea_ac_lan#182]
### Device type and model (or SN)

11

### The description of new feature

Cannot connect to host api.github.com:443 ssl:default [None]

**Comment by wuwentao** [comment]
@jonny77 你的HA无法访问github网站，确认你的这台机器能够正常连接github，否则不能使用hacs的自动下载功能。
需要手动下载release页面中的压缩包，解压缩后放到指定的目录去运行。

**Comment by wuwentao** [comment]
这个问题和HA或者当前integration没有任何关系，我先关闭issue了，请确保你的设备能够正常访问github即可。
