### ISSUE TITLE
Unable to switch to this repo 

### ISSUE THREAD

**Issue by patman-cp** [wuwentao/midea_ac_lan#186]
### HA core version

2024.6.4

### Integration version

0.3.22 (old repo)

### Device type and model

Air Conditioner 00000Q1B

### Used App

homeassistant

### The description of problem

Not really a bug or new feature but not sure where to ask about this, I asked here with no response:

https://community.home-assistant.io/t/switch-from-hacs-current-github-com-georgezhao2010-midea-ac-lan-to-github-com-wuwentao-midea-ac-lan/743233

HA: 2024.6.4
HACS: 1.34.0
Integration (that I don't want to use): https://github.com/georgezhao2010/midea_ac_lan/releases/tag/v0.3.22

I'm currently using the above unsupported version that was installed via HACS.

I added this one as a custom repository, but it's still using the other version and I don't see a way to delete the old version.

How can I switch to this repo?

Thanks :-D

**Comment by mbohdal** [comment]
this worked for me:
run the terminal in home assistant and do this:
`
cd /config/custom_components/midea_ac_lan
rm -rf *
wget https://github.com/wuwentao/midea_ac_lan/releases/download/v0.4.2/midea_ac_lan.zip
unzip midea_ac_lan.zip
`
and then reboot home assistant, after reboot the new repo was used, but I did not lost any configurations, the AC devices are still visible in home assistant and still work

**Comment by chemelli74** [comment]
> How can I switch to this repo?

Those steps should work fine:

- Remove the old repo from HACS
- Add the new repo from HACS
- Force component redownload from HACS

**Comment by patman-cp** [comment]
Thanks, I got it working!

I'm not sure what you meant by "Force component redownload from HACS":
- Stopped my instance of HA / docker
- removed the old / unsupported repo via command line
- Started my instance
- removed the custom repo via the HACS UI
- added back the custom repo via the HACS UI
- restarted HA.

Kind of odd as there must have been two instances of midea_ac_lan somewhere - I don't mean the whole repo or such but HACS had the built-in one and a custom repo listed.

**Comment by patman-cp** [comment]
Actually it's still not working - it looks like the old one is still showing up, could be some docker image overwriting my changes. I have to look closer.

**Comment by patman-cp** [comment]
OK I did not actually download the custom repository, did that and restarted and now all is good.
