### ISSUE TITLE
浴霸能够被识别但添加失败

### ISSUE THREAD

**Issue by Helloookimi** [wuwentao/midea_ac_lan#187]
### HA版本

2023.8.2

### 集成版本

0.4.2

### 设备类型及型号

Appliance code:210006726130388; 210006725916239; 208907214486645

### 使用的App

美的美居

### 问题详细描述

Appliance code	Type	IP address	SN	Supported
210006726130388	26	10.*.*.*	000026511M010003239281100*******	YES
210006725916239	26	10.*.*.*	000026511M010003239281100*******	YES
208907214486645	26	10.*.*.*	000026511M010003239281100*******	YES

以上3个浴霸为同一型号的美的Y5W，在添加设备时能够正常识别显示210006725916239 (Bathroom Master)，选择美的美居登陆，提交后就显示无法连接到指定设备，但同账号下的2台油汀添加没有问题。这个问题困扰很久了，从当初georgezhao2010一直至今，始终无法添加这几个设备，请大佬看看是为什么如有任何需要请随时联系，万分感谢。

**Comment by chemelli74** [comment]
@Helloookimi, was intentional to close the issue right after opening it ?
