### ISSUE TITLE
浴霸能够识别但是无法添加

### ISSUE THREAD

**Issue by Helloookimi** [wuwentao/midea_ac_lan#188]
### HA版本

2023.8.2

### 集成版本

0.4.2

### 设备类型及型号

Appliance code:210006726130388; 210006725916239; 208907214486645

### 使用的App

美的美居

### 问题详细描述

Appliance code	Type	IP address	SN	Supported
210006726130388	26	10.*.*.*	000026511M010003239281100*******	YES
210006725916239	26	10.*.*.*	000026511M010003239281100*******	YES
208907214486645	26	10.*.*.*	000026511M010003239281100*******	YES

以上3个浴霸为同一型号的美的Y5W，在添加设备时能够正常识别显示210006725916239 (Bathroom Master)，选择美的美居登陆，提交后就显示无法连接到指定设备，但同账号下的2台油汀添加没有问题。这个问题困扰很久了，从当初georgezhao2010一直至今，始终无法添加这几个设备，请大佬看看是为什么如有任何需要请随时联系，万分感谢。

**Comment by Helloookimi** [comment]
日志里当我提交以后会有一条：2024-06-30 14:52:57.704 DEBUG (MainThread) [custom_components.midea_ac_lan.config_flow] Try to get the Token and the Key use the preset MSmartHome account

**Comment by chemelli74** [comment]
Hi @Helloookimi, please add the full log not just 1 line.

Please add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

And add diagnostics (menu configuration -> integration -> midea_ac_lan -> download diagnostics )

**Comment by wuwentao** [comment]
@Helloookimi 请先更新到最新的v0.5.0版本，重新添加设备试试。
建议先根据首页提升，开启midea_ac_lan和midealocal的debug log，然后执行相关操作，并反馈一下结果。

再根据这个结果，对比添加成功和添加失败的设备，实际获取到的硬件以及软件版本信息差异，随后看看是否能够找出解决办法。

**Comment by leonvvip** [comment]
估计跟我提交的是同一个问题

**Comment by chemelli74** [comment]
Please we need data, now wild guesses.

**Comment by Helloookimi** [comment]
Upgraded to the latest version, when adding, it prompts Can't get available token for this device, and there is a Can't get valid token with input account in Midea Mercure server in the log, and then the following key is used c414e631394b8639@outlook.com to get this account instead of my mobile phone account. The attached is a log file, thank you very much. Please feel free to contact me if you need anything.
[home-assistant_2024-07-11T13-11-26.325Z.log](https://github.com/user-attachments/files/16193770/home-assistant_2024-07-11T13-11-26.325Z.log)
 if you need anything

**Comment by rokam** [comment]
Inside your log I can find:
`2024-07-11 21:09:25.580 DEBUG (MainThread) [midealocal.cloud] Midea cloud API url: https://mp-prod.smartmidea.net/mas/v5/app/proxy?alias=/v1/iot/secure/getToken, data: {'udpid': '54af9f51ce38a49a49da060c15d679dd', 'reqId': 'f58837f724ea9646b06b91d83c7723c6', 'stamp': '20240711130925'}, response: b'{"msg":"\xe8\xb0\x83\xe7\x94\xa8\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xbc\x82\xe5\xb8\xb8(\xe8\xae\xbf\xe9\x97\xae\xe5\x9c\xb0\xe5\x9d\x80\xe4\xb8\x8d\xe5\xad\x98\xe5\x9c\xa8) [no Route matched with those values]","code":40404}'`

This means that we're trying to retrieve keys in an invalid endpoint. We need a sniffing on the network to correctly identify what is wrong.

**Comment by Helloookimi** [comment]
what can I do for next? Do you need access my local network for test or I sniffing the network by myself? What kind of information  need to identify what is wrong? thank u for u helps.

**Comment by Helloookimi** [comment]
I can priviod a remote desktop by rustdesk for you do any test run. windows or mac both fine. Please help to solve this problem. Thanks a million for the help!

**Comment by Helloookimi** [comment]
Or I could try to make a packet capture of the network and upload this part of the packet file. Please tell me what you need do for next,remote or packet file upload, thank u .

**Comment by rokam** [comment]
I need a capture for that endpoint. That happens between your mobile and the cloud.

**Comment by Helloookimi** [comment]
That happens between your mobile and the cloud. It's means you need a capture which is the app when I login with my account and do some remote control?

**Comment by rokam** [comment]
Yes, thats it

**Comment by Helloookimi** [comment]
I send an email for you(lucas@mindello.com.br).with  capture file. pls tell me what need for next, if you need any other information. thank u.

**Comment by wuwentao** [comment]
@rokam @Helloookimi  it should be encrypted data with TLS/SSL, so we can't directly sniffer the packets.
and I also tried with inject with the client app to do MIMT some months ago, it also not works, client will report error and can't do any control, maybe Meiju using v2 api,it's cloud service. both client app and server have the cert check.

**Comment by Helloookimi** [comment]
Is that means cannot add those drives into ha any more? When I do the packet capture yesterday, find that cannot use andriod with Packet Capture. The app are no network when VPN set up.

**Comment by wuwentao** [comment]
> Is that means cannot add those drives into ha any more? When I do the packet capture yesterday, find that cannot use andriod with Packet Capture. The app are no network when VPN set up.

yes, there is no any good solution now,  and we should have some new solution.

**Comment by wuwentao** [comment]
由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 #275 来跟踪和处理，避免大量重复问题的跟踪和处理。
当然，当前issue仍然可以继续更新和发送其他消息

**Comment by wuwentao** [comment]
补充说明：close当前issue仅仅是不在默认open的issue list中显示，并不代表当前issue不再处理或者无视问题了。
主要是方便管理和跟踪其他issue，而当前issue的后续状态和进展，仍然可以继续update其他信息，都是能够收到提醒和状态更新的。
并且，在主issue中也都有当前issue的关联信息，后续都能逐个追踪，回溯回来。

**Comment by lynnliuy** [comment]
我遇见了同样的问题，也是y5w的设备

**Comment by chemelli74** [comment]
Please reference to issue #275 as reuqested.
