### ISSUE TITLE
Add an option for -1/+1 degree change instead of +-.5

### ISSUE THREAD

**Issue by Buniculbroscoi** [wuwentao/midea_ac_lan#191]
### Device type and model (or SN)

Inventor Omnia Eco

### The description of new feature

Some Ac's do not support .5 temperature changes, it would be good if upon the configuration step, we could choose the behavior.

**Comment by chemelli74** [comment]
Please read carefully the documentation. You can customize the setting.

**Comment by wuwentao** [comment]
same issue as https://github.com/wuwentao/midea_ac_lan/issues/177
please check with the readme and document.
we can close this issue

**Comment by patman-cp** [comment]
I added a temperature_step of 1 to my "Customize", and in the debug logs I see:

```
homeassistant    | 2024-07-06 15:37:40.772 DEBUG (ImportExecutor_0) [midealocal.device] [151732604698822] Status update: {'temperature_step': 1}
```

But, adjusting the temperature still only happens in .5 degress Fahrenheit increments, but my AC unit only allows changes of 1 degree Fahrenheit.

Using Midea AC device info 00000Q1F.

Is this working OK for others?

**Comment by erikgieseler** [comment]
The same problem exists with the C3 heat pump waterheater. 
In HA you can adjust the temperature of the waterheater in 0.5° steps, but the heat pump only supports 1° steps. 
Adding "{ "temperature_step": 1 }" does not bring any change.

**Comment by wuwentao** [comment]
@patman-cp if it still can't work for your device.
1. you should enable debug log and attach the full log , not only paste one line msg
2. add your device detail info,  there is still sub type for 0xAC device, please share your device detail with `cat /config/.storage/midea_ac_lan/151732604698822.json`

**Comment by patman-cp** [comment]
Full logs:

[ha_logs.txt](https://github.com/user-attachments/files/16119833/ha_logs.txt)

I don't have a separate file for their config, I have this in my .storage/core.config_entries:

[midea_part_of_config.json](https://github.com/user-attachments/files/16119835/midea_part_of_config.json)

**Comment by chemelli74** [comment]
> The same problem exists with the C3 heat pump waterheater. In HA you can adjust the temperature of the waterheater in 0.5° steps, but the heat pump only supports 1° steps. Adding "{ "temperature_step": 1 }" does not bring any change.

Please add only `{"temperature_step": 1}` ( no external double quotes ) and report back.

**Comment by wuwentao** [comment]
@patman-cp you MUST have `.storage/midea_ac_lan/xxx.json` , so why you missed it?  you have manual removed it after you add your device?


and please also follow the right instraction from the document like chemilli74 provide to you and confirm your setting is right.

another question is : when you increase the temperature step, is your device works in power on status?  as from the log, seems it's power off not works in exepect result? or you can confirm it works in power on mode and only the status result is error from the log.

as there is more error in log file, like `Error in process message` and `Does not supports the protocol MessageQueryAppliance, ignored`

so please confirm the action/status can works well in your device and it got the expect action/status,then we can continue check the temperature_step error.

**Comment by erikgieseler** [comment]
> > The same problem exists with the C3 heat pump waterheater. In HA you can adjust the temperature of the waterheater in 0.5° steps, but the heat pump only supports 1° steps. Adding "{ "temperature_step": 1 }" does not bring any change.
> 
> Please add only `{"temperature_step": 1}` ( no external double quotes ) and report back.

I had already inserted this without the external double quotes.

**Comment by patman-cp** [comment]
> you MUST have `.storage/midea_ac_lan/xxx.json` , so why you missed it? you have manual removed it after you add your device?

There is no file there:

```
umbrella:/config# 
umbrella:/config# find /config -name midea_ac_lan
/config/.storage/midea_ac_lan
/config/custom_components/midea_ac_lan
umbrella:/config# 
umbrella:/config# ls -la /config/.storage/midea_ac_lan
total 4
drwxr-xr-x    2 root     root             6 Jul  9 08:30 .
drwxr-xr-x    3 root     root          4096 Jul 20 06:46 ..
```

> another question is : when you increase the temperature step, is your device works in power on status? as from the log, seems it's power off not works in exepect result? or you can confirm it works in power on mode and only the status result is error from the log.

Yes.

But one of the two Midea AC units I have connected is not working right, the "Midea Guest Room" one. I don't know if it's a hardware or software issue, and not sure how to debug it - this is generating the errors like you mentioned.
