### ISSUE TITLE
AttributeError: 'MideaC3Climate' object has no attribute '_modes'

### ISSUE THREAD

**Issue by erikgieseler** [wuwentao/midea_ac_lan#196]
### HA core version

2024.6.4

### Integration version

0.4.3

### Device type and model

C3 - Heat Pump Wi-Fi Controller 171H120F

### Used App

SmartHome

### The description of problem

After updating to version 0.4.3, the error message appears in the log:
`AttributeError: 'MideaC3Climate' object has no attribute '_modes'`

### The logs

[_homeassistant_logs.txt](https://github.com/user-attachments/files/16070482/_homeassistant_logs.txt)

**Comment by chemelli74** [comment]
Thx for reporting. We are looking at it right now.

**Comment by erikgieseler** [comment]
Downgrading to 0.4.1 has made it functional again.

**Comment by erikgieseler** [comment]
After adding the section following `# Defining _modes attribute` in the file climate.py (0.4.3) in the class MideaC3Climate(MideaClimate) it works for me again:

```
class MideaC3Climate(MideaClimate):
    """Midea C3 Climate Entries."""

    _device: MideaC3Device

    _powers: ClassVar[list[C3Attributes]] = [
        C3Attributes.zone1_power,
        C3Attributes.zone2_power,
    ]

    def __init__(self, device: MideaC3Device, entity_key: str, zone: int) -> None:
        """Midea C3 Climate entity init."""
        super().__init__(device, entity_key)
        self._zone = zone
        self._attr_hvac_modes = [
            HVACMode.OFF,
            HVACMode.AUTO,
            HVACMode.COOL,
            HVACMode.HEAT,
        ]
        self._power_attr = MideaC3Climate._powers[zone]
        
        # Defining _modes attribute
        self._modes = {
            0: HVACMode.OFF,
            1: HVACMode.AUTO,
            2: HVACMode.COOL,
            3: HVACMode.HEAT,
        }

    # Rest of the class remains unchanged
```

However, the source code should still be checked.
