### ISSUE TITLE
To do List

### ISSUE THREAD

**Issue by wuwentao** [wuwentao/midea_ac_lan#2]
### Device type and model (or SN)

To do List 

### The description of new feature

- [x]  1. fork and sync with new code changes   [done]
- [x] 2. add github action to auto release midea_ac_lan.zip  [done]
- [x]  3. add more Collaborator in current repo   [done]
- [ ] 4. remove old **midea_ac_lan** from HACS default integration
- [ ] 5. add new **midea_ac_lan** repo to HACS default integration
- [x] 6. add github action lint  all the codes in PR, also include old source code linter error fix.
- [ ] 7.  add testcase script, it also may cost more time to do, but I will continue track with it.
- [x] 8. disable push to master branch and only accept PR
- [x]  9. repo mixed with both CRLF and LF in source code, convert all the CRLF file to LF format.
- [x] 10. disabled default commit merge method and only use squash and rebase merge
- [ ]  11. github lint action disabled PYLINT and MYPY checks as there is too many error, will be continue fix in future

In additional, we have more contributers to continue work with it now.
I have add @rokam @attilaersek @Necroneco @chemelli74 @Qianli-Ma as collaborators to current repo.

All of use can merge PR in future and we don't need to worry about the merge permission controlled in one people.

**Comment by wuwentao** [comment]
Stauts update: 

job 4: remove old midea_ac_lan from HACS

I have submit issue and PR：
https://github.com/hacs/integration/issues/3682
https://github.com/hacs/default/pull/2504

it may cost more time to finished job 4 and job 5 
 once job 4 done ,  I will add new forked repo to HACS default integration later.


Job 6,  in progress, i will fix  some linter erro with all the old source code, once it down , I will deploy to mater branch and used by all PR and future.

**Comment by chuppito** [comment]
Hello, if there is an update from the previous developer, how do I install this version?

**Comment by wuwentao** [comment]
> Hello, if there is an update from the previous developer, how do I install this version?

I'm not sure with the upate, if he can continue maintain it, he can merge current chagnes in this repo, and we also can merge the new changes from any repo.
Don't need to worry about this issue

**Comment by chuppito** [comment]
The translation was bad. I meant how to install your repo. I noticed that the salaries function to program activation times is missing.

**Comment by wuwentao** [comment]
> The translation was bad. I meant how to install your repo. I noticed that the appointements function to program activation times is missing.

got it, you mean how to manual install with current repo.
i have submit hacs PR to remove old repo and add current repo, seems it will cost a long time, there is too many PR pending and I'm not sure with the finish time now.
but I will continue to push it to hacs official repo based on the official progress.

in addition, I have upate the README docs in current repo, you can check the detail and confirm with it:
[installation](https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#installation)

if there is any new issue,  I think we can file new issue to track with it.
then we can use issue to track the bug and quickly fix it via PR.

**Comment by chuppito** [comment]
thank you for the explanations I was able to go to your repository.  do you know how to retrieve the programming like on the Smarthome application?  failing that I did it via the on and off button but if I can leave the water heater on without it heating up that would be a real added value thank you for the work provided

**Comment by chemelli74** [comment]
What about using a [Discord](https://discord.com/invite/home-assistant) group for easier communication ?

My contact is : `chemelli74#2180`

**Comment by wuwentao** [comment]
> What about using a [Discord](https://discord.com/invite/home-assistant) group for easier communication ?
> 
> My contact is : `chemelli74#2180`

Thank you very much , I have request to add you as friend, my username is `wuwentao2000`,  and I also create a init discord group: https://discord.com/invite/ZWdd2fXndn

finished init setting and no any more changes, we can have a try.

**Comment by rokam** [comment]
I've already connected and did request friend.
