### ISSUE TITLE
小乌梅 TG100RVIC 无法连接到指定设备

### ISSUE THREAD

**Issue by zhaojianwen12** [wuwentao/midea_ac_lan#200]
### 设备类型及型号 (或SN)

0000DB513381284113B185XXXXXXXXXX

### 新功能的描述

无法连接到指定设备，请求大哥添加

**Comment by wuwentao** [comment]
请给出详细错误信息，同时请按照首页readme最后一部分的debug说明，在configuration.yaml中开启midea_ac_lan和midealocal的debug log，重启HA，然后再添加设备，然后将完整log文件上传上来吧。

**Comment by zhaojianwen12** [comment]
[home-assistant_midea_ac_lan_2024-07-04T01-02-58.452Z.log](https://github.com/user-attachments/files/16092102/home-assistant_midea_ac_lan_2024-07-04T01-02-58.452Z.log)
日志文件已上传，麻烦大哥了

**Comment by zhaojianwen12** [comment]
> 请给出详细错误信息，同时请按照首页readme最后一部分的debug说明，在configuration.yaml中开启midea_ac_lan和midealocal的debug log，重启HA，然后再添加设备，然后将完整log文件上传上来吧。

大哥日志已上传

**Comment by zhaojianwen12** [comment]
> 多谢，日志显示美的美居登录成功，获取设备token成功，但是使用token去连接设备失败，导致不能添加成功。 目前还不清楚具体原因，随后看看是否可以做一些其他方面的尝试。

谢谢大哥，如果有需要我可以告诉美的相关账号信息以及配合测试

**Comment by rokam** [comment]
Can you plese try v.0.5.0 and provide new logs?

**Comment by kern111** [comment]
![
[home-assistant_2024-07-16T06-43-33.539Z.log](https://github.com/user-attachments/files/16244138/home-assistant_2024-07-16T06-43-33.539Z.log)
2024_07_16_14_24_51](https://github.com/user-attachments/assets/c503c04c-dd53-4a09-bd64-c7f6a2eb28f5)
我也是小乌梅洗衣机，sc83。可以获取令牌，但是还是添加不上，试了好几次都不行

**Comment by kern111** [comment]
重新上传一个日志
[home-assistant_midea_ac_lan_2024-07-16T07-03-53.221Z.log](https://github.com/user-attachments/files/16244342/home-assistant_midea_ac_lan_2024-07-16T07-03-53.221Z.log)

**Comment by rokam** [comment]
0.5.4 should fix your issue

**Comment by zhaojianwen12** [comment]
使用0.5.4版本后，添加洗衣机直接提示Can't get available token for this device，日志如下，麻烦大哥看一下
[home-assistant_midea_ac_lan_2024-07-16T07-03-53.221Z.log](https://github.com/user-attachments/files/16321739/home-assistant_midea_ac_lan_2024-07-16T07-03-53.221Z.log)

**Comment by rokam** [comment]
This doesn't make any sense.  Your device ID 210006728726061 on IP 192.168.100.200 is connecting fine, but when you try to add ID 210006726031471 on IP  192.168.100.172 it is identified as device 210006728726061. There is something strange in your configuration.
I do suggest you to clear every configuration, remove all files inside `.storage/midea_ac_lan` this might solve your issue.

**Comment by rokam** [comment]
Also, the file attached is from before 0.5.4.

**Comment by zhaojianwen12** [comment]
您好，按照您的方法尝试后，还是提示上述错误

**Comment by rokam** [comment]
Can you please provide updated logs, those you've provided are from before 0.5.4..

**Comment by zhaojianwen12** [comment]
[Uploading home-assistant_midea_ac_lan_2024-07-22T15-41-11.654Z.log…]()

**Comment by rokam** [comment]
@zhaojianwen12 the upload failed.

**Comment by wuwentao** [comment]
抱歉，由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 #275 来跟踪和处理，避免大量重复问题的跟踪和处理。

**Comment by wuwentao** [comment]
补充说明：close当前issue仅仅是不在默认open的issue list中显示，并不代表当前issue不再处理或者无视问题了。
主要是方便管理和跟踪其他issue，而当前issue的后续状态和进展，仍然可以继续update其他信息，都是能够收到提醒和状态更新的。
并且，在主issue中也都有当前issue的关联信息，后续都能逐个追踪，回溯回来。
