### ISSUE TITLE
C3 Heat pump - Waterheater wrong temperature_steps

### ISSUE THREAD

**Issue by erikgieseler** [wuwentao/midea_ac_lan#207]
The same problem exists with the C3 heat pump waterheater.
In HA you can adjust the temperature of the waterheater in 0.5° steps, but the heat pump only supports 1° steps. 
Adding `{ "temperature_step": 1 }` does not bring any change.

_Originally posted by @erikgieseler in https://github.com/wuwentao/midea_ac_lan/issues/191#issuecomment-2212453735_

**Comment by wuwentao** [comment]
@erikgieseler you don't need to open both duplicate issue.
just reopen old issue.
close current and only keep one.

**Comment by wuwentao** [comment]
There is no temperature_step and Customize feature in C3 device now.

**Comment by rokam** [comment]
PR open on lib side: https://github.com/rokam/midea-local/pull/209
