### ISSUE TITLE
Can't add Midea dishwasher MFD60S510Wi

### ISSUE THREAD

**Issue by nikhomekgn** [wuwentao/midea_ac_lan#21]
**Versions**
Midea AC LAN 0.3.23
HA with latest updates

**Description**
Sorry for my bad English. I have Midea dishwasher MFD60S510Wi (static IP), when adding a device to HA it is automatically found, but when confirming I see a message in the form "The configuration is incorrect". If changing model to correct - same message. 
Log in configuration.yaml enabled, but there's nothing in it.
If use Protocol V1 or V2 device is adding to HA, but all sensors are unavailable. Log attached below.
P.S. Integration update to alfa version available in HA, but it won't download.

![02](https://github.com/wuwentao/midea_ac_lan/assets/159110821/5f248b19-a8cc-46a0-ae28-7bd046bddfad)
![03](https://github.com/wuwentao/midea_ac_lan/assets/159110821/d5f80c3f-ecd7-4ae9-9bd8-8564c3524318)
![04](https://github.com/wuwentao/midea_ac_lan/assets/159110821/e0c78363-5fda-4661-81fc-8dfc482ac4ee)
![05](https://github.com/wuwentao/midea_ac_lan/assets/159110821/a3fb58a0-0303-4057-9e4d-8993ec592b0e)
![06](https://github.com/wuwentao/midea_ac_lan/assets/159110821/c00e4c3c-29a8-4d52-b9aa-803faa5a1e01)

**Comment by wuwentao** [comment]
Thank you for youre issue report, as most of us just take it and we may need time to check and fix it later.

**Comment by nikhomekgn** [comment]
Thanks for your work. If any information is needed on this issue, I will try to provide as much information as possible.

**Comment by nikhomekgn** [comment]
HA core version
2024.5.5

Integration version
v0.4.1

Device type and model
Dishwasher Midea MFD60S510Wi (latest firmware)

Used App
Midea SmartHome and Home Assistant

The description of problem
Upgrade integration to 0.4.1 and clear config in /.storage/midea_ac_lan
Try to connect:
![1](https://github.com/wuwentao/midea_ac_lan/assets/159110821/c9c2957b-4395-46dc-81af-4eb1f9c9d0fd)
Same if use "auto"
![2](https://github.com/wuwentao/midea_ac_lan/assets/159110821/cca0d07c-d4ed-49f7-828c-ee69170aa60a)
![3](https://github.com/wuwentao/midea_ac_lan/assets/159110821/b8e783ea-b24c-479d-9823-869ebd110d24)
![4](https://github.com/wuwentao/midea_ac_lan/assets/159110821/5fd6aa42-0253-4179-b714-5d57db65a943)

In Midea SmartHome app I see a message "Account logged in somewhere else"
In /.storage folder midea_ac_lan is not created

In home-assistant.log is nothing about midea_ac_lan. Debug is enabled in configuration.yaml.

If I try to connect manually:
![5](https://github.com/wuwentao/midea_ac_lan/assets/159110821/67d3a468-7358-4997-bb27-d2739a67e4f4)

Maybe I do something wrong?

**Comment by wuwentao** [comment]
no debug log should be an issue....

you can remove this integration and reboot HA, remove all the /configs/.storage/mides_ac_lan/

then reinstall it, after install, please confirm you have enabled debug log for midea_ac_lan from /configs/configuration.yaml file.

enable command can be found in readm.md file 

once debug log can works, you can attack the debug log file, then we can check the detail error

**Comment by nikhomekgn** [comment]
Reinstall integration, reboot HA
In configuration.yaml add

```python
logger:
default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midea_local: info
```

Log, that repeats every time I try to add a device
[homeassistant.log](https://github.com/user-attachments/files/15746216/homeassistant.log)

**Comment by nikhomekgn** [comment]
Remove integration. Install 0.4.2
Debug log:
[homeassistant.log](https://github.com/user-attachments/files/15934610/homeassistant.log)

**Comment by chemelli74** [comment]
Thx, I debugged the issue and login fails because of

`{'msg': 'user route does not exist', 'code': 10004}`

I think there is a change in MSSmartCloud change

**Comment by nikhomekgn** [comment]
Thanks for your feedback!
Is the problem on my side or do I need to wait for some changes in the code?

**Comment by ttrueten** [comment]
Hello,
Same problem here with a Midea SU 5.35X14CS.

I hope you can find a solution. 
Best regards,
T.

**Comment by chemelli74** [comment]
I think I got it, probably we release a new version in a few days

**Comment by chemelli74** [comment]
Please check with v0.4.3 and if still experience the issue, add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

**Comment by nikhomekgn** [comment]
Update to 0.4.3
[homeassistant.log](https://github.com/user-attachments/files/16076876/homeassistant.log)

**Comment by chemelli74** [comment]
`2024-07-03 08:56:14.649 DEBUG (MainThread) [midealocal.device] [153931628223465] Authentication failed`

Please double check with **SmartHome mobile app** that you can login.

**Comment by nikhomekgn** [comment]
In SmartHome in that time (translated):
_09:11
Account logged in somewhere else
Your account has been registered on another device in Other. If you do
not do this yourself, please sign out of this device by visiting Manage
Sign-In Devices._

![screenshot](https://github.com/wuwentao/midea_ac_lan/assets/159110821/d944ab14-66c1-447c-9715-e5a8907d4a9c)

**Comment by ttrueten** [comment]
> Please check with v0.4.3 and if still experience the issue, add the following to `configuration.yaml` , restart HA, and post the log:
> 
> ```yaml
> logger:
>   default: warning
>   logs:
>     custom_components.midea_ac_lan: debug
>     midealocal: debug
> ```
Hi there,
Thank you for your work, unfortunately no noticeable change. Log attached, username anonymized, login with the real data via the SmartHome app works.

HTH,
T.
> 
> Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.
recent:///b8bac2509f9fc5261e893a6566850610

**Comment by ttrueten** [comment]
Hi there,
thank you for your work, unfortunately no noticeable change. Log attached, username anonymized, login with the real data via the SmartHome app works.

HTH,
T.
[homeass.log](https://github.com/user-attachments/files/16080489/homeass.log)

**Comment by chemelli74** [comment]
Unfortunately I don't think we can do something if authorization fails.

**Comment by rokam** [comment]
``@wuwentao and @chemelli74 I think this is a case that the 2nd key retrieval type might work. If this is true, https://github.com/rokam/midea-local/pull/200 should solve it.

**Comment by rokam** [comment]
Can you please try v.0.5.0?

**Comment by ttrueten** [comment]
"Can't get available token for this device"
[homeass.log](https://github.com/user-attachments/files/16141305/homeass.log)

**Comment by nikhomekgn** [comment]
Install 0.5.0
"Can't get available token for this device"
[homeassistant.log](https://github.com/user-attachments/files/16143675/homeassistant.log)

**Comment by ttrueten** [comment]
Same behaviour: Can't get available token for this device

[homeass.log](https://github.com/user-attachments/files/16146541/homeass.log)

**Comment by chemelli74** [comment]
@nikhomekgn , @ttrueten which mobile app are you using to control your devices ?
We need exact name (and maybe a screenshot of the icon just to be sure ).

**Comment by nikhomekgn** [comment]
Screen from "About"
![Screenshot_20240710_040956_SmartHome](https://github.com/wuwentao/midea_ac_lan/assets/159110821/7a682f14-cee5-4d63-98d7-3a4bb12602e8)

**Comment by wuwentao** [comment]
all the token can't work for these 0xE1 device.
the same error as 0xDB device

**Comment by nikhomekgn** [comment]
Is this solvable?
Maybe you need some additional information from me?

**Comment by ttrueten** [comment]
> @nikhomekgn , @ttrueten which mobile app are you using to control your devices ? We need exact name (and maybe a screenshot of the icon just to be sure ).
file:///home/tht/.config/Signal/attachments.noindex/1b/1bda73636afbe1e8dade7d4eb5c3a951c18a3641a4d599e2481cc95c31c64ea5

**Comment by nikhomekgn** [comment]
I understand that update 0.5.3 does not solve our problem, but I'm attach the log just in case
[homeassistant.log](https://github.com/user-attachments/files/16200053/homeassistant.log)

**Comment by rokam** [comment]
0.5.4 should fix your issue

**Comment by nikhomekgn** [comment]
@rokam updating to 0.5.4 did not help
[homeassistant.log](https://github.com/user-attachments/files/16257612/homeassistant.log)

**Comment by wuwentao** [comment]
由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 https://github.com/wuwentao/midea_ac_lan/issues/275 来跟踪和处理，避免大量重复问题的跟踪和处理。
当然，当前issue仍然可以继续更新和发送其他消息
