### ISSUE TITLE
DataSignDoesntMatch exception since 0.5.0

### ISSUE THREAD

**Issue by sanderlv** [wuwentao/midea_ac_lan#224]
### HA core version

2024.7.2

### Current integration version

0.5.1

### Last known working integration version

0.4.3

### Device type and model

Dehumidifier 00000Q17 (0) by Midea & Dehumidifier 00000Q12 (0) by Midea 

### Used App

none

### The description of problem

Since 0.5.0 and now also on 0.5.1 I have issues with both appliances.

They are "unavailable" most of the time.

Logger: midealocal.device
Source: /usr/local/lib/python3.12/site-packages/midealocal/device.py:596
First occurred: 19:26:26 (1 occurrences)
Last logged: 19:26:26

[146235046613512] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 572
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 572, in run
    result = self.parse_message(msg)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 385, in parse_message
    messages, self._buffer = self._security.decode_8370(self._buffer + msg)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/midealocal/security.py", line 356, in decode_8370
    raise DataSignDoesntMatch
midealocal.exceptions.DataSignDoesntMatch

### The logs

https://dpaste.org/683kn

**Comment by sanderlv** [comment]
How do I disable logging via call service?

**Comment by sanderlv** [comment]
I "think" but not sure that Dehumidifier 00000Q12 (0) by Midea has "no issues" since this is "online" a while now. Only the Dehumidifier 00000Q17 (0) by Midea will not come online...

**Comment by rokam** [comment]
This log is incomplete. I can't see the issue in the integration. Can you please provide full log?

**Comment by sanderlv** [comment]
Please help me how to do

**Comment by rokam** [comment]
> Please help me how to do

https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#debug

**Comment by sanderlv** [comment]
https://dpaste.org/jWmFr

I have reloaded 2 times here... hope this helps

**Comment by rokam** [comment]
Have you tried 0.5.2? Can you please install midea-local lib locally?
`pip install midea-local`

Then run `midealocal discover --host 192.168.20.3 -d`

**Comment by sanderlv** [comment]
I only see 0.5.1...?

**Comment by sanderlv** [comment]
Ok 0.5.2 installed. Now both mideas are not working anymore :-(

**Comment by chemelli74** [comment]
When reporting an issue, always attach fresh debug log

**Comment by sanderlv** [comment]
I added 2 fresh debug logs... all was so fine before 0.5.0 I really miss that... How to get back?

**Comment by sanderlv** [comment]
Fresh log: https://dpaste.org/mmEPw

**Comment by rokam** [comment]
The root cause is the failure to retrieve capabilities. This should fix https://github.com/rokam/midea-local/pull/217

**Comment by sanderlv** [comment]
I would love this to be fixed again... I rely on this marvelous piece of sw

**Comment by rokam** [comment]
@sanderlv can you confirm 0.5.3 fixes the issue?

**Comment by sanderlv** [comment]
Hi, currently I reverted to 0.4.3 and all works. I will test after holiday period asap. Thanks in advance!

**Comment by sanderlv** [comment]
0.5.4 fixes! Thank you!
