### ISSUE TITLE
Support current humidity level

### ISSUE THREAD

**Issue by domoritz** [wuwentao/midea_ac_lan#23]
### Device type and model (or SN)

dehumidifier, 00000Q1B

### The description of new feature

https://github.com/wuwentao/midea_ac_lan/blob/master/doc/A1.md supports setting the humidity level but doesn't show the current level.

Another integration supports showing the current humidity so it would be nice to do that here as well.

Having the current humidity level would allow the widget on the left. 

<img width="791" alt="Screenshot 2024-05-25 at 13 14 38" src="https://github.com/wuwentao/midea_ac_lan/assets/589034/1e92e5dc-ce6f-415d-8b46-beb002913042">

**Comment by Necroneco** [comment]
Hello, please have a try. #78
