### ISSUE TITLE
Device status unknown 

### ISSUE THREAD

**Issue by Yeahoover** [wuwentao/midea_ac_lan#231]
### HA core version

2024.7.2

### Current integration version

v0.5.2

### Last known working integration version

v0.4.3

### Device type and model

Dehumidifier 00000Q12 (0)

### Used App

NetHome Plus

### The description of problem

Hi there,

I have updated the integration and since then the device status switches to unknown more or less directly after a reload. I have removed the device and added it again. Some behavior. I switched on debug log and pasted what I found. I hope this is enough:
Logger: midealocal.device
Quelle: /usr/local/lib/python3.12/site-packages/midealocal/device.py:239
Erstmals aufgetreten: 11:21:16 (1 Vorkommnisse)
Zuletzt protokolliert: 11:21:16

[153931628307436] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 219
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 219, in connect
    self.refresh_status(wait_response=True)
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 344, in refresh_status
    raise SocketException
midealocal.exceptions.SocketException

Thanks!

### The logs

[Logger midealocal device.txt](https://github.com/user-attachments/files/16174379/Logger.midealocal.device.txt)

**Comment by chemelli74** [comment]
> ### Last known working integration version
> last version before update

We need the version you was using, `last` is not an identifier.

**Comment by 22kW** [comment]
Same here
[midea.log](https://github.com/user-attachments/files/16174503/midea.log)

**Comment by chemelli74** [comment]
Use the thump up in the issue opening, no need to write "same here" is just overwhelming notifications.

**Comment by Yeahoover** [comment]
Sorry, first time I open an issue. I don't know the previous version I had. Is there a way to find it out without loading a backup?
[home-assistant_midea_ac_lan_2024-07-11T09-48-51.056Z.log](https://github.com/user-attachments/files/16174615/home-assistant_midea_ac_lan_2024-07-11T09-48-51.056Z.log)

**Comment by wuwentao** [comment]
@Yeahoover 
firt of all: this device work well in previous midea_ac_lan ? all the status and control action also works well?
just to confirm you had used it to control device pass and check status.

I'm not sure with your old configs and whethere you have edit some configs.

we can recheck with below steps:  

1. remove this device from HA web UI from midea_ac_lan
2.  you need to login HA terimal via ssh or just Terminal add-on from the web UI 
3.  run this command `cat /config/.storage/midea_ac_lan/153931628307436.json` in ssh or Terminal
4. copy the file content output and share it to us in current issue, also used as a config backup.
5. continue delete this backup file with run `rm -rf /config/.storage/midea_ac_lan/153931628307436.json`

once it done, all the env is clear now, make sure you have enabled midea_ac_lan and midealocal debug log (got it from README in current repo), restart HA.

add your device and confirm it again.

it used to confirm you are not using an error configs file,  for example, if your device is v3 and you just manual add it with v2, it still can add pass.

after got this check, if it still can't works, you can use HACS to rollback to a old version to confirm it again.
you can select the version number via HACS--> Midea_AC_LAN --> redownload action in the right top of the page with three dot.

**Comment by Yeahoover** [comment]
Hi, sorry, I do not fully understand what you want me to do.

I restored a backup to get Home Assistant Core back to 2024.7.1 and this integration to v0.4.3 and it worked again (I get the status and I an execute actions on it).
 I only updated this integration to v0.5.2 and it shows the described error.

**Comment by syntesys87** [comment]
I have HAOS version 2024.7.1, tried to redownload 0.4.3 version, full reboot and working.

**Comment by rokam** [comment]
https://github.com/rokam/midea-local/pull/217 should fix it

**Comment by rokam** [comment]
@syntesys87 is v0.5.3 working?

**Comment by Yeahoover** [comment]
@rokam I updated to v0.5.3 (and Home Assistant Core 2024.7.2), The status can now be read, but actions do not work.
[home-assistant_midea_ac_lan_2024-07-13T07-41-52.045Z.log](https://github.com/user-attachments/files/16201272/home-assistant_midea_ac_lan_2024-07-13T07-41-52.045Z.log)

**Comment by rokam** [comment]
Can you please follow the instrutions from readme to enable debug?

**Comment by Yeahoover** [comment]
@rokam 
[home-assistant_midea_ac_lan_2024-07-13T12-32-26.127Z.log](https://github.com/user-attachments/files/16202156/home-assistant_midea_ac_lan_2024-07-13T12-32-26.127Z.log)

**Comment by rokam** [comment]
@Yeahoover without complete logs we aren't able to identify the root cause of the issue. Your logs are partial and they have almost the same content.

**Comment by Yeahoover** [comment]
I switched the debug on as explained in the read me. I don't know what else to do. maybe somebody else can provide a log.

**Comment by Yeahoover** [comment]
@rokam I had to restore an older backup because my history suddenly stopped working. Backup was from before I ever had any issues with the integration. I upgraded Home Assistant Core to 2024.7.2 and after that the integration to v0.5.3. Everything works for me now (Status and Actions).

**Comment by syntesys87** [comment]
@Yeahoover also for me seems working, launched from remote, I'll test in 5-6 hours at home.

**Comment by eldonzo** [comment]
I'm still having issues, even automatic configuration doesn't work well, it gives me same information for the two AC split I have...
Unfortunately I don't have a working backup, any advice on how can I reset the situation to making it work again?

**Comment by rokam** [comment]
@eldonzo your error might be a different one. Please open an issue and attach a complete log.
