### ISSUE TITLE
Make minimum HA version less that latest

### ISSUE THREAD

**Issue by holocronweaver** [wuwentao/midea_ac_lan#24]
### HA core version

2024.4.4

### Intergration version

0.3.23

### Device type and model

n/a

### Used App

n/a

### The description of problem

A recent commit bumped the minimum required HA version to 2024.5 while correcting the HACS filename (mieda -> midea). 2024.5 is latest as of this writing. I did not see anything in the commit that indicated why this was done, and nothing jumped out as actually requiring 2024.5 per se.

Could we restore original minimum version of 2022.5? Or least something less recent than latest where [some users are reporting issues with](https://community.home-assistant.io/t/2024-5-just-a-little-bit-smaller). Maybe 2023.1 since it is the required version in the README?

### The logs

n/a

**Comment by chemelli74** [comment]
I think there are a few deprecations on older code.
Anyway, if we are moving to integrate into core, it will auto-solve itself ;-)

**Comment by wuwentao** [comment]
yes, thanks all , we may need time to fix it and continue improve it.

**Comment by holocronweaver** [comment]
@wuwentao Thanks! Would you mind making a new release so users in older HA versions can download the add-on via HACS?

**Comment by wuwentao** [comment]
> @wuwentao Thanks! Would you mind making a new release so users in older HA versions can download the add-on via HACS?

yes, we also did more code changes, will check and confirm the detail later, may be these days, sorry for the delay.

**Comment by wuwentao** [comment]
@holocronweaver after confirm with rokam, i have create a v0.4.0 release, please help to check and confirm. thanks!

**Comment by holocronweaver** [comment]
@wuwentao Works, thank you!
