### ISSUE TITLE
滚筒洗衣机 错误提示Can't get available token for this device

### ISSUE THREAD

**Issue by kern111** [wuwentao/midea_ac_lan#243]
### HA版本

2024.7.1

### 集成版本

v0.5.4

### 之前可正常使用的集成版本

无

### 设备类型及型号

TG100v88

### 使用的App

美的美居

### 问题详细描述

v0.53可以获取设备密匙，但是无法添加上，更新到v0.54，无法获取密匙了。
![微信图片_20240717113833](https://github.com/user-attachments/assets/8b9d306a-5d8f-4786-b19f-c9afb4167ae2)
![2024_07_17_11_39_57](https://github.com/user-attachments/assets/28d32af8-eda8-409e-86e0-ad82c36cd361)

### The logs

[home-assistant_midea_ac_lan_2024-07-17T03-32-08.265Z.log](https://github.com/user-attachments/files/16258871/home-assistant_midea_ac_lan_2024-07-17T03-32-08.265Z.log)

**Comment by wuwentao** [comment]
v0.5.3和v0.5.4结果应该都一样，都是无法成功添加设备，目前的信息来看，可能暂时没有发现差异信息和对应这些差异信息的解决办法，可能需要后续其他的解决办法。

**Comment by wuwentao** [comment]
抱歉，由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 #275 来跟踪和处理，避免大量重复问题的跟踪和处理。

**Comment by wuwentao** [comment]
补充说明：close当前issue仅仅是不在默认open的issue list中显示，并不代表当前issue不再处理或者无视问题了。
主要是方便管理和跟踪其他issue，而当前issue的后续状态和进展，仍然可以继续update其他信息，都是能够收到提醒和状态更新的。
并且，在主issue中也都有当前issue的关联信息，后续都能逐个追踪，回溯回来。
