### ISSUE TITLE
HomeKit not working correctly

### ISSUE THREAD

**Issue by jcastro** [wuwentao/midea_ac_lan#247]
### HA core version

2024.7.2

### Current integration version

0.5.4

### Last known working integration version

none

### Device type and model

Air Conditioner 00000Q12 (44204)

### Working mobile app

MSmartHome

### The description of problem

Hi!
I've set up and successfully controlled my AC; however, when I pass these devices to HomeKit, it's not showing any information, and it shows as "No response". It might not be a bug in the integration, but in HomeKit, but just wanted to check. Thanks a lot!

<img width="338" alt="image" src="https://github.com/user-attachments/assets/97a10097-849d-484f-b50f-2199377b496a">

### The logs
[home-assistant_2024-07-18T11-22-53.326Z.log](https://github.com/user-attachments/files/16282502/home-assistant_2024-07-18T11-22-53.326Z.log)

**Comment by rokam** [comment]
Hi @jcastro , we need debug logs to identify the root cause of your issue. In the readme there are instructions how to enable debug logs.

**Comment by jcastro** [comment]
> Hi @jcastro , we need debug logs to identify the root cause of your issue. In the readme there are instructions how to enable debug logs.
[home-assistant_2024-07-18T11-22-53.326Z.log](https://github.com/user-attachments/files/16282441/home-assistant_2024-07-18T11-22-53.326Z.log)

thanks @rokam ! let me know if this helps

**Comment by jcastro** [comment]
I did a screen recording, when opening the device it shows 22º (which is the current set temperatura) but I can't controll anything about it

https://github.com/user-attachments/assets/a2a7c45a-453c-4714-a0a8-bf8f0c833a15

**Comment by rokam** [comment]
I don't know homekit. However the log shows that it is correctly communicating with your device.

**Comment by jcastro** [comment]
Yes I can control it no problem with HA!Sent from my iPhoneOn 18 Jul 2024, at 15:40, Lucas Mindêllo de Andrade ***@***.***> wrote:﻿
I don't know homekit. However the log shows that it is correctly communicating with your device.

**Comment by rokam** [comment]
So, the issue is between homekit and homeassistant.
