### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Schnitzelsep** [wuwentao/midea_ac_lan#253]
### HA core version

2024.7.3

### Current integration version

0.5.4

### Last known working integration version

0

### Device type and model

Dishwasher

### Working mobile app

MSmarthome

### The description of problem

Unknown error by Download

### The logs

Unknown error

**Comment by rokam** [comment]
Can you provide a print?

**Comment by Schnitzelsep** [comment]
Now I can start Setup-Assistent and login with Msmarthome Data. The Device found but "Can't get available token for this device“ see screenshot.

￼

**Comment by wuwentao** [comment]
could you try with msmart app ? and not MSmarthome? then update the result to us.
thanks!

**Comment by Schnitzelsep** [comment]
There is no msmart app in the app store for iOS and there is a new version of MSmarthome. This is now called Smarthome (without M). I tested all the others that are available NethomePlus, Homeconnect, Aqara Home, Eve and SmartLife but they don't find the Midea dishwasher

**Comment by wuwentao** [comment]
sorry, this is my mistaken, it should be SmartHome.
you can update to latest version, and  follow the README document to enable DEBUG log, then upload the debug log file to us confirm it again.
we can got more details with debug log file
Thanks

**Comment by wuwentao** [comment]
sorry, this is my mistaken, it should be SmartHome.
you can update to latest version, and  follow the README document to enable DEBUG log, then upload the debug log file to us confirm it again.
we can got more details with debug log file
Thanks

**Comment by wuwentao** [comment]
@Schnitzelsep  any update? could you help to upload the full debug log file when error exist to confirm the reason?

**Comment by Schnitzelsep** [comment]
I'm sorry but I haven't tried again and won't try again because it doesn't work. I have a new Homeassistand installation and no more logs from the integration. Thanks anyway for the support.

**Comment by wuwentao** [comment]
ok, we will close this issue.
if there is any new issue in future ,you can reopen it or report new bug with debug log and latest version.
thanks.
