### ISSUE TITLE
必须要打开power实体才能控制空调

### ISSUE THREAD

**Issue by GavinIves** [wuwentao/midea_ac_lan#257]
### 集成版本

0.5.4

### 之前可正常使用的集成版本

无

### 设备类型及型号

HL1PRO Air Conditioner 22040057 (44204) HE1PRO Air Conditioner 22040055 (44204) 小冰棒2代柜机 Air Conditioner 22270063 (32773)

### 使用的App

美的美居

### 问题详细描述

<img width="334" alt="image" src="https://github.com/user-attachments/assets/3c6371a2-06f3-4095-8fb6-659b4bc4c6f7">
这几台空调都必须把电源power这个实体启用 才可以操作空调调制冷制热等功能 但是其实我更希望实体能够简洁一点。
其次这几台空调设定模式 实际会生效但在HA中依然显示关闭 但是如果用美的美居打开 HA这里会显示对应的状态模式。貌似和信息发送之后没有等足够的时间就去询问空调现在的模式。在xiaomigateway3这个插件中也有过类似的问题

**Comment by wuwentao** [comment]
你的意思是切换模式时或者选择模式时，就直接自动去把设备power on 然后再切换到对应的模式？避免分别操作二次？对吧？
也就是现在的功能逻辑和物理遥控器一样，必须先按电源键，再按模式健。

**Comment by GavinIves** [comment]
不是这个原因导致的 已关闭
