### ISSUE TITLE
Power use reported incorrectly?

### ISSUE THREAD

**Issue by Kyesarri** [wuwentao/midea_ac_lan#258]
### HA core version

2024.7.2

### Current integration version

v0.5.4

### Last known working integration version

v0.5.4

### Device type and model

Air Conditioner 00000Q1A (8)

### Working mobile app

Midea Air

### The description of problem

Currently both my AC are displaying KW/H as usage, the numbers reported to home assistant from this integration are not correct, at least for my units.

I've tried all three power_analysis_method values, all which are reporting odd values. Value 1 is the closest to what I assume the devices should be consuming - however the value is returning x10 what I believe the consumption is. 

![snip_292x367_2024-07-2441-38](https://github.com/user-attachments/assets/154ad93a-2b97-4bc5-b13a-84a9bb945098)

I believe these values should be reported as Watts / Kilowatts in the first place. 

Further information:

Brand: Carrier
Serial: 000000P0000000Q1A8407D879EB70000
Model Name: Carrier Allure Split System Inverter Hi Wall 3.5kW
Model Number: 42QHG035N8 / 38QHG035N8 (outdoor)

If there is any more information I can provide / tests I can perform please let me know.

**Comment by rokam** [comment]
Energy consumption is expected to be kWh. Realtime power will be reported as W/kW.
