### ISSUE TITLE
HA升级2024.5.2后美的空调实体变不可用，也无法重新添加

### ISSUE THREAD

**Issue by billzlw** [wuwentao/midea_ac_lan#26]
### HA版本

2024.5.2

### 集成版本

v0.4.0-alpha

### 设备类型及型号

美的风管机

### 使用的App

美的美居

### 问题详细描述

美的风管机星光科技版，之前添加控制都正常，ha升级到2024.5.2之后空调实体变得不可用，其余美的设备全部正常，删除空调实体后无法重新添加，自动添加或通过IP添加都找不到设备，有办法修复或解决吗？

**Comment by rokam** [comment]
Can you provide logs?

**Comment by CharmingCheung** [comment]
我上周也遇到了相同的问题，也是删除再添加都找不到，但应该跟这个集成没关系。
你可以试试把你的空调断开网络再重连，比如重启路由器和wifi，又或者断开风管机的供电再重连，问题就解决了。

**Comment by wuwentao** [comment]
@billzlw 

我初步猜测，觉得可能和设备配置文件缓存有关系，需要您进行确认。

在midea ac lan这个integration 中选择添加设备按钮，有三个选项，第一个是discovery，第二个应该是manual，选择其中最后一个，应该是list device，试试看，记不住了，拿手机回复的，来回切换不方便！
让他从list这里查看，是否可以显示您的风管机设备信息，如果有的话，提供一下显示的设备id，再给您后续操作说明。

**Comment by Hyominnnn** [comment]
@wuwentao 我遇到的问题是空调跟热水器实体变不可用，删除后重新添加又正常了，但是可能过个1-2天又变成不可用了

**Comment by wuwentao** [comment]
> @wuwentao 我遇到的问题是空调跟热水器实体变不可用，删除后重新添加又正常了，但是可能过个1-2天又变成不可用了

感谢反馈，这个确实比较诡异……
尤其是过1-2天变成不可用，如果变成不可用的话，应该会有log记录，建议直接开启debug log，然后持续观察看看哪里的错误吧，尤其是第一个报错的地方，后续的错误可能是因为第一个错误影响导致的。

另外您的HA版本是否升级了？当前midea_ac_lan的版本等信息，也需要都明确一下，HA版本升级一般不会考虑向前兼容，都需要同步更新和升级。
或者一直维持HA和midea_ac_lan均为老版本不升级。

**Comment by wuwentao** [comment]
由于长时间未收到任何反馈或者回复，先关闭这个issue了，如果仍然有问题，可以随时reopen，

如果仍然无法添加，请附上相应的版本信息，并根据首页reamdme添加debug log的配置，重启HA，然后执行相关的操作，触发错误log，然后下载debug log文件，上传到issue中。
