### ISSUE TITLE
"Screen Display" not working for my device

### ISSUE THREAD

**Issue by HamsenBender** [wuwentao/midea_ac_lan#264]
### Device type and model (or SN)

Inventor Aria AC 000000P0000000Q1AC93C4XXXXXXXXXX

### The description of new feature

I assume the extra controls "Screen Display" and "Screen display Alternate"  are to disable the LED's on the AC indoor unit?
Would be really nice if it worked for my device also. I am able to disable the LED's through the remote control.
Is this possibleN

**Comment by rokam** [comment]
Some devices only support disabling the LED through the remote. Do your AC support disabling through the app?

**Comment by HamsenBender** [comment]
> Some devices only support disabling the LED through the remote. Do your AC support disabling through the app?

You are correct, disabling the LED is not available in the app as far as I can see, only through the remote. So then I guess it can't be controlled through the interface. Thanks for your swift response
