### ISSUE TITLE
空调的风速不支持控制

### ISSUE THREAD

**Issue by 1074748905** [wuwentao/midea_ac_lan#283]
### 设备类型及型号 (或SN)

Air Conditioner 22040055 (44204)

### 新功能的描述

不支持风速控制，功能挺重要的，要是支持就好了。多谢

**Comment by wuwentao** [comment]
@1074748905 看了看功能描述，同时对比了一下当前的实现，应该是支持风速控制的。
在extra的fan mode里面，支持silent/low/medium/high/full/auto等档位，每个档位的风速比例如下源码定义：

```
self._fan_speeds: dict[str, int] = {
            FAN_SILENT: 20,
            FAN_LOW: 40,
            FAN_MEDIUM: 60,
            FAN_HIGH: 80,
            FAN_FULL_SPEED: 100,
            FAN_AUTO: 102,
        }
```
