### ISSUE TITLE
Carrier Air Functions missing

### ISSUE THREAD

**Issue by 0Styless** [wuwentao/midea_ac_lan#286]
### 设备类型及型号 (或SN)

Air Conditioner 152832116261152 / 142936511613277

### 新功能的描述

152832116261152 > SN: 000000P0000000Q1A8407DXXXXXXXXXX
142936511613277 > SN: 000000P0000000Q13C2093XXXXXXXXXX

In the old integration maintained by georgezhao2010 there were functions that are now missing.

For example:

* Turn off/Turn on acoustic beep when devices get turned on / off
* A sensor that shows if the devices are full of dust

Is there any chance to get this features back?

**Comment by wuwentao** [comment]
for AC devices,  seems there is a [Prompt Tone] switch to turn on/off the prompt tone when power on/off, and also include all the actions.

I'm not sure with the sernsor that show if the device is full of dust,  need to confirm with it later.

**Comment by wuwentao** [comment]
just checked with the source code, both should available.
you may need to configure and enable both in your device extra sensors and extra controls.

just follow the README document:
https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#extra-sensor-and-switch-entities

also have AC device document:
https://github.com/wuwentao/midea_ac_lan/blob/master/doc/AC.md

please hlep to check.

if issue still exist and these feature can't work, you can report bug for us.
Thanks
