### ISSUE TITLE
Does not set FanEntityFeature.TURN_OFF/TURN_ON 

### ISSUE THREAD

**Issue by kovacsla** [wuwentao/midea_ac_lan#287]
### HA core version

2024.8.2

### Current integration version

v0.5.7

### Last known working integration version

???

### Device type and model

Air Conditioner 00000Q1C 

### Working mobile app

NetHomePlus

### The description of problem

Does not set FanEntityFeature.TURN_OFF/TURN_ON but implements the turn_off/turn_on method.

Log:

WARNING (MainThread) [homeassistant.components.fan] Entity midea_ac_lan.146235046500478_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method.
WARNING (MainThread) [homeassistant.components.fan] Entity midea_ac_lan.146235046500478_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method.

**Comment by wuwentao** [comment]
thanks,
https://github.com/wuwentao/midea_ac_lan/pull/285 should fix this warning message.
still in progress.

**Comment by wuwentao** [comment]
fixed, it should be available in next release version, thanks!
