### ISSUE TITLE
求大佬支持MQXF350Ⅱ新风设备

### ISSUE THREAD

**Issue by eggleader-zhang** [wuwentao/midea_ac_lan#296]
### 设备类型及型号 (或SN)

0000005112429652937220XXXXXXXXXX

### 新功能的描述

美的新风设备支持，目前会被识别成AC，我看了AC的ReadMe中有提到某些新风会使用空调的协议，但是这款新风接入后任何操作都不生效。大佬如有需要抓包，我可以试着帮忙抓一下，谢谢！

**Comment by wuwentao** [comment]
如果设备自动扫描识别后显示的类型为AC，说明确实使用的是AC类型的协议。
请提供完整SN。
也就是美居app里面的产品品类，型号，SN等详细信息。

**Comment by eggleader-zhang** [comment]
> 如果设备自动扫描识别后显示的类型为AC，说明确实使用的是AC类型的协议。 请提供完整SN。 也就是美居app里面的产品品类，型号，SN等详细信息。

![IMG_1765](https://github.com/user-attachments/assets/b18065cb-8ccc-4ef6-9581-bb3473dc7e95)
产品品类：美的新风
产品型号：MQXF350 2代
SN：0000005112429652937220XXXXXXXXXX
多谢大佬

**Comment by wuwentao** [comment]
@eggleader-zhang 设备SN不能马赛克，需要用类型+SN来匹配唯一的设备信息，要不我也编不出来一个实际能够匹配你真实设备的SN。

**Comment by eggleader-zhang** [comment]
> @eggleader-zhang 设备SN不能马赛克，需要用类型+SN来匹配唯一的设备信息，要不我也编不出来一个实际能够匹配你真实设备的SN。

完整的序列号：0000005112429652937220340014U2D3 😊

**Comment by wuwentao** [comment]
多谢，我忘了一件事，可能还需要确认设备是可以添加的，如果没有可用的token，目前可能也会比较尴尬。

step 1. 局域网任意PC安装midea-local库: `pip3 install -U midea-local`   (看看是否linux主机，是否需要加sudo执行，或者使用pip命令代替pip3，根据实际情况选择吧）

step 2: 在局域网尝试discover设备，并使用token验证: `python3 -m midealocal.cli discover -d --host 192.168.x.x` 修改这个ip地址为你设备对应的IP地址，还请将执行中打印的debug信息，复制并保存为log文件，一并附件上传一下吧，感谢。

如果step2执行有报错，可以尝试指定美居的用户名和密码试试，例如 `python3 -m midealocal.cli discover -d  --cloud-name  美的美居 --username your_username  --password your_password --host 192.168.x.x` 修改为你的账号和密码即可。

**Comment by eggleader-zhang** [comment]
> 多谢，查了一下，这个SN的control/query都使用的和AC设备不一样，我忘了一件事，可能还需要确认设备是可以添加的，如果没有可用的token，目前可能也会比较尴尬。
> 
> step 1. 局域网任意PC安装midea-local库: `pip3 install -U midea-local` (看看是否linux主机，是否需要加sudo执行，或者使用pip命令代替pip3，根据实际情况选择吧）
> 
> step 2: 在局域网尝试discover设备，并使用token验证: `python3 -m midealocal.cli discover -d --host 192.168.x.x` 修改这个ip地址为你设备对应的IP地址，还请将执行中打印的debug信息，复制并保存为log文件，一并附件上传一下吧，感谢。
> 
> 如果step2执行有报错，可以尝试指定美居的用户名和密码试试，例如 `python3 -m midealocal.cli discover -d --cloud-name 美的美居 --username your_username --password your_password --host 192.168.x.x` 修改为你的账号和密码即可。

携带账号密码和不携带账号密码的方式我都试了，拿到token了，但是好像没发成功连接，日志见附件。
[with_account.log](https://github.com/user-attachments/files/16762388/with_account.log)
[without_account.log](https://github.com/user-attachments/files/16762389/without_account.log)

**Comment by wuwentao** [comment]
你这描述有点尴尬，你这个设备明显应该是可以添加成功的，并且可以解析大部分AC空调相关的功能的，但是少部分新风相关的操作或者功能不生效吧？
所以前面这一堆描述信息和沟通都是浪费时间和无意义的，因为从描述来看，我理解是这个设备完全不支持，不能添加成功，任何功能都不可用，实际上应该并不是……

**因此，请准确描述和表达清楚你的问题所在和预期的功能，而不是整个设备的支持xxx，任何操作不生效，那具体是什么操作？否则没人知道你在描述啥问题**： 
1.设备目前是否能够添加成功，从debug log看应该是毫无问题的，请确认。
2.设备添加成功后，目前能够用的功能（或者忽略也行），
3.重点和核心：添加成功以后，目前主要不能用的功能，美居app里面支持的功能，并且希望添加的功能（一个一个来，分类准确清晰，描述具体一些，因为只有用设备的人才知道，其他人并不知道你在干嘛。 配合美居app里对应功能截图也可以。

**注意**，开启midea_ac_lan和midealocal的debug log，然后在midea_ac_lan里面执行相关操作，触发错误，如果没有相关功能，则提供一些添加成功以后，操作其他功能或者预期想要的功能，上传完整debug log即可。因为目前从已有debug log能够看到：Does not supports the protocol MessageNewProtocolQuery, ignored
但是其他基本功能，例如电源开关，温度显示，提示音开关，等，目前看起来应该是能够解析成功并且可能可以控制的。

**Comment by rokam** [comment]
@wuwentao it looks like the MIN_AUTH_RESPONSE as 20 doesn't comply with his device. It is returning 13 bytes.

**Comment by wuwentao** [comment]
@rokam no, I don't think it's a problem, this cli tools will try with all the method 1 + method 2 token/key.
from the log, we can found the method 1 token/key is passed, and you just saying method 3 token/key is invalid, so we can ignored method 2 token.

and the debug log is enough, this device should add pass and there is a `Does not supports the protocol MessageNewProtocolQuery, ignored`, it can't parse body_type `b1`, and still can parse body_type `bb`.
we only need to add support for parse `b1` body_type message.
it's enough.

so we still need the device details and feature requirements.

**Comment by eggleader-zhang** [comment]
> 你这描述有点尴尬，你这个设备明显应该是可以添加成功的，并且可以解析大部分AC空调相关的功能的，但是少部分新风相关的操作或者功能不生效吧？ 所以前面这一堆描述信息和沟通都是浪费时间和无意义的，因为从描述来看，我理解是这个设备完全不支持，不能添加成功，任何功能都不可用，实际上应该并不是……
> 
> **因此，请准确描述和表达清楚你的问题所在和预期的功能，而不是整个设备的支持xxx，任何操作不生效，那具体是什么操作？否则没人知道你在描述啥问题**： 1.设备目前是否能够添加成功，从debug log看应该是毫无问题的，请确认。 2.设备添加成功后，目前能够用的功能（或者忽略也行）， 3.重点和核心：添加成功以后，目前主要不能用的功能，美居app里面支持的功能，并且希望添加的功能（一个一个来，分类准确清晰，描述具体一些，因为只有用设备的人才知道，其他人并不知道你在干嘛。 配合美居app里对应功能截图也可以。
> 
> **注意**，开启midea_ac_lan和midealocal的debug log，然后在midea_ac_lan里面执行相关操作，触发错误，如果没有相关功能，则提供一些添加成功以后，操作其他功能或者预期想要的功能，上传完整debug log即可。因为目前从已有debug log能够看到：Does not supports the protocol MessageNewProtocolQuery, ignored 但是其他基本功能，例如电源开关，温度显示，提示音开关，等，目前看起来应该是能够解析成功并且可能可以控制的。

大佬不好意思，刚有时间回复你这个问题。
我想要的主要是开关功能，虽然日志中显示扫描到了开关，但是这个开关实际只能关，开是无效的，按照您提供的方法，我抓出了开和关设备的请求体

关机：{'header': 'aa3aac00000000000805', 'body': 'bb3000ffff11000000000800000000000000000000013c000000000000000000000000000000000000000000000022c1', 'message type': '05', 'body type': 'bb'}
开机：{'header': 'aa6aac00000000000803', 'body': 'bb6000ffff1080808080000000280a00000000000000000000000000003000000000000000000002008e00000000000000000002000000000000000000000000010f00480d03000000000000000000000000000000003130303030300030ca60', 'message type': '03', 'body type': 'bb'}

完整的日志在这里，我重复进行了几次开关。
我看起来好像开启的时候，还携带了一些其他设备没有的特殊信息。
[home-assistant_midea_ac_lan_2024-09-01T14-01-35.363Z.log](https://github.com/user-attachments/files/16829152/home-assistant_midea_ac_lan_2024-09-01T14-01-35.363Z.log)

![E0152C22-777B-471C-89E8-6495F0FEDE4F_1_102_o](https://github.com/user-attachments/assets/ac3d5221-b07a-436f-93df-0db9786a823c)

**Comment by wuwentao** [comment]
@eggleader-zhang 
你这仍然是一堆问题，首先，也是核心问题：从你提供的debug log，你压根不是使用现在的midea_ac_lan啊，你还是使用的`georgezhao2010/midea_ac_lan/`

你不能拿一个很老的版本过来，然后报一个新的bug？说xxx不行，xxx不支持，然后提供的log也完全对不上啊。
对吧？拜托，大哥，请稍微专业和仔细一点啊！

其次，从你提供的debug log来看，你压根就没有在HA里面操作开机或者关机，log里面都没有相关操作记录。

请使用正确的版本，并且使用正确的操作，你应该的报bug，安装githubissue模板和要求提交bug，而不是把一个bug按支持xxx功能来处理，二者完全不是一回事。

因此，完全文不对题了，一直在做无效沟通和无效debug，浪费时间和精力。

**Comment by wuwentao** [comment]
@eggleader-zhang 
请尽快根据问题需求，反馈最新的状态和debug log，目前issue已经超过一个月未收到任何状态更新。
如果后续仍然无任何回复，将close当前issue。
