### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'recv'

### ISSUE THREAD

**Issue by jove01** [wuwentao/midea_ac_lan#297]
### HA core version

2024.8.3

### Current integration version

v0.5.7

### Last known working integration version

?

### Device type and model

Air Conditioner 00000Q1C (44204)

### Working mobile app

MSSmarHome

### The description of problem

After Installing this fork, see the error below

`Logger: midealocal.device
Quelle: /usr/local/lib/python3.12/site-packages/midealocal/device.py:561
Erstmals aufgetreten: 11:08:34 (2 Vorkommnisse)
Zuletzt protokolliert: 11:08:39

[18691697955959] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 528
[18691697955958] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 528
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 528, in run
    msg = self._socket.recv(512)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'recv'`

**Comment by wuwentao** [comment]
@jove01  thanks for your bug report.

could you help to enable `midea_ac_lan` and `midealocal` debug log via **README** document, and upload a full debug **log file** with this error msg?
attach a debug log file and NOT paste the log text in issue, thanks.

**Comment by chemelli74** [comment]
Logging reports **midealocal**, I think it should be opened on library side

**Comment by wuwentao** [comment]
@jove01 
it should be fix with latest release v0.5.8, please upgrade and confirm the result.
close current issue, if the same issue still exist, we can continue update in current issue or reopen it later.

**Comment by jove01** [comment]
Thanks for the Update
