### ISSUE TITLE
does not set FanEntityFeature.TURN_OFF

### ISSUE THREAD

**Issue by jove01** [wuwentao/midea_ac_lan#298]
### HA core version

2024.8.3

### Current integration version

v0.5.7

### Last known working integration version

?

### Device type and model

Air Conditioner 00000Q1C (44204)

### Working mobile app

MSmarHome

### The description of problem

After installing this fork

`Logger: homeassistant.components.fan
Quelle: components/fan/__init__.py:295
Integration: Lüfter (Dokumentation, Probleme)
Erstmals aufgetreten: 11:04:34 (12 Vorkommnisse)
Zuletzt protokolliert: 11:08:38

Entity midea_ac_lan.18691697955959_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
Entity midea_ac_lan.18691697955959_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
Entity midea_ac_lan.18691697955958_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues
Entity midea_ac_lan.18691697955958_fresh_air (<class 'custom_components.midea_ac_lan.fan.MideaACFreshAirFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/wuwentao/midea_ac_lan/issues`

**Comment by wuwentao** [comment]
thank you very much for your bug report,  it should be the same issue as #287  and has  been fixed by #285 .
please doube check with next release version.
so I will close current issue.
once new release published, please have a try with it(we still not publish it, please wait for some days, sorry)
if issue still exist with next version, you can reopen current issue or directly add new log in current issue.
