### ISSUE TITLE
High CPU usage after update

### ISSUE THREAD

**Issue by Juffle74** [wuwentao/midea_ac_lan#315]
### HA core version

2024.9.2

### Current integration version

0.5.8

### Last known working integration version

Last one before 0.5.8

### Device type and model

Air Conditioner 00000Q18 (44204)

### Working mobile app

MSmartHome

### The description of problem

After 0.5.8 update, CPU usage of "Home Assistant core" stay at around 20% until I deactivate Midea AC Lan.

I've tried reinstall, reboot, etc multiple time but as soon as the integration is active, CPU usage go up again and stay high even after more that 1 hour.

**Comment by yyax** [comment]
不光cpu占用高，homeassistant还会卡死，所有设备失联

**Comment by yyax** [comment]
> 不光cpu占用高，homeassistant还会卡死，所有设备失联
https://github.com/wuwentao/midea_ac_lan/issues/291#issuecomment-2364767854

**Comment by alawadhi3000** [comment]
Same issue, one CPU core is stuck at 100% and HA UI is laggy.

**Comment by lyfqdl** [comment]
+1
本来以为只有空调冰箱等温度实体不更新数据的问题。
看了楼主发的问题后，确实有CPU占用过高的问题。
我用的虚拟机，当时只是感觉到查看历史数据加载时间会很长，原来是这个原因(CPU占用过高)。

**Comment by erikgieseler** [comment]
I have the same problem. 
After a downgrade to 0.5.7 everything was fine again. 
Here is a corresponding log from 0.5.8.
[home-assistant.log](https://github.com/user-attachments/files/17083710/home-assistant.log)

**Comment by robimarko** [comment]
I also have an issue with 0.5.8 causing weird issues with UI and load on Pi 4.

**Comment by wuwentao** [comment]
thank you for the bug report, this is really a breaking changes, and we did some process related changes for it, as my local test env have multipe CPUs in a x86 ENV, so I didn't found this high cpu usage issue,  sorry.
anyway, we will check it and try to fix it quickly.

**Comment by Lunmingpei** [comment]
same problem, my cpu is N3150.

**Comment by wuwentao** [comment]
fixed, waitting for approve and merge.
once id done, v0.5.9 will publish and quickly fix this high cpu issue.

**Comment by wuwentao** [comment]
@robimarko @alawadhi3000 @yyax @lyfqdl @Lunmingpei @erikgieseler @Juffle74 
please upgrade with latest release and confirm the result, thanks

**Comment by lyfqdl** [comment]
感谢修复。更新到0.59，解决了以上问题。暂未发现其他问题。 @wuwentao

**Comment by Juffle74** [comment]
Fixed, thank you for the update!

**Comment by lyfqdl** [comment]
貌似温度传感器更新频率有问题，有时候长时间不更新

**Comment by wuwentao** [comment]
> @wuwentao Fixed, thank you for the update amd your work!

you are welcome

**Comment by wuwentao** [comment]
> 貌似温度传感器更新频率有问题，有时候长时间不更新 @wuwentao

感谢反馈，我也进一步观察后续问题，如果问题比较明显或者严重影响使用，可以继续提交其他新的issue，尽量提供完整debug log和详细说明。

新增功能或者修改代码，永远可能伴随bug出现，不过后续都会持续不断迭代新功能和版本，因此新增功能不可避免会引入新问题，但是都会尽快修复和解决。
但是，目前项目也存在多个人员协同工作，不同的人对不同的问题会有不同的理解，也难免都会引入各种问题，同时也有不少review机制，会有不少流程方面的延迟。
但是bug的出现和正确的通过issue反馈，才方便更好的解决问题，不断完善功能。

**Comment by yyax** [comment]
cpu占用问题已解决。
