### ISSUE TITLE
Bug(Device): 美的理想家三代从0.3.22升级到0.5.9后个别房间温度传感器显示未知

### ISSUE THREAD

**Issue by lirong6845** [wuwentao/midea_ac_lan#318]
### HA core version

2024.9.2

### Current integration version

0.5.9

### Last known working integration version

0.3.22

### Device type and model

Air Conditioner 22396525 (44204)，Air Conditioner 22396533 (44204)

### Working mobile app

美的美居

### The description of problem

之前3.22那个版本只是有几个功耗控制显示未知，其它所有功能，控制都正常。空调才安装耗电大，看到有电耗实体可添加，就想着能不能看看电耗情况。但是那个版本显示未知。几经波折找到这个最新版本，想看看能不能用。结果好些控制不能用。室内外温度、温度显示不正常。

### The logs

[home-assistant_midea_ac_lan_2024-09-22T02-11-25.330Z.log](https://github.com/user-attachments/files/17087993/home-assistant_midea_ac_lan_2024-09-22T02-11-25.330Z.log)
下面这个是以前那个版本的，也麻烦看看是机器本身不支持还是这个型号必须接外机485接口才能看到功耗数据。
[home-assistant_midea_ac_lan_2024-09-15T13-57-01.497Z.log](https://github.com/user-attachments/files/17087996/home-assistant_midea_ac_lan_2024-09-15T13-57-01.497Z.log)

在其它地方看到过同型号能支持功耗监测，见下图
![v2-1b6205886323415a5b2d56a9431ac1bb_r](https://github.com/user-attachments/assets/f8d0eebb-c02d-443e-9943-48226c95a477)
原文地址：https://zhuanlan.zhihu.com/p/651016447

**Comment by wuwentao** [comment]
@lirong6845 感谢反馈bug，先别着急，有问题不要紧，咱们逐个问题来看，逐个解决即可。
但是目前你的描述比较杂乱，我简单看了看log，设备也有好几台，而目前说的，**具体是哪个功能不能用，也就是哪个设备的哪个操作不行，还有哪个设备的哪个显示不正常，都未明确说明到底是哪台设备**，也就是你log里面的，之前用的什么【次卧】【小次卧】，新的log里面又是什么【客厅】【中央空调】，因此，请一个一个来。
逐个明确目前版本对应的问题，哪些功能有异常或者不能用，或者之前哪个功能是正常的，现在不正常了，先得把问题都理清楚，描述准确了，才能去针对性的看。

另外，关于电量统计，是否能够支持，一般都是看设备出厂是否包含相应的模块，一般来说，美居app直接能够查看到电量统计信息的，基本都是可以统计的，但是美居上不支持的，大概率是不支持……仅仅是少部分新款升级，在过渡期间，可能有一些新款老款交替过渡的时期可能出现吧，这个随后实际试试有没有数据就基本可以明确，没有数据一般就是没有电量统计模块，这是靠硬件模块实现的，不是软件加一下就行的事，因此需要理性对待。
