### ISSUE TITLE
Out of chart cpu usage after update

### ISSUE THREAD

**Issue by Rihan9** [wuwentao/midea_ac_lan#326]
### HA core version

2024.9.2

### Current integration version

0.5.9

### Last known working integration version

0.5.7

### Device type and model

-

### Working mobile app

-

### The description of problem

Hi,
I have a microcomputer used a server with a ryzen 5 5500U (6C/12T).
After the update to the version 0.5.8 and 0.5.9 the cpu usage for home assistant jump from 4% to 100% (due to python limitation, home assistant cannot use more than 1 cpu unit). 
The rest of the home assistant instance became quite unstable (automation don't start or their execution got cut, unresponsive device etc).

I have the cprof and the out file from the profiler integration if you want it. They are quite eavy file to read, so I'm not sure if you want them. To sum up the important point of them, they reported over 35M call for 2 minute log to device:663:_check_heartbeat, using 49% of the total cpu time, and 729 calls to selector:445:select using 54% of the total cpu time. I don't know if these are from your integration or the are totally normal numbers.

**Comment by wuwentao** [comment]
@Rihan9 could you double check with your installed version?  or just reinstall **v0.5.9** and reboot your HA to confirm again
**v0.5.9** should fix the high cpu usage issue, and v0.5.8 should have this high cpu usage issue.
thanks
