### ISSUE TITLE
Component is not reconnecting automatically on an outage

### ISSUE THREAD

**Issue by Bonabrux** [wuwentao/midea_ac_lan#327]
### HA core version

2024.9.3

### Current integration version

0.5.7

### Last known working integration version

(before plug-in was taken over by wuwentao) 

### Device type and model

Air conditioner 00000Q18 (-84)

### Working mobile app

SmartHome

### The description of problem

For time to time (randomly), or on a power outage the ac device gets disconnected from the integration (HA and Wi-Fi has UPS but the ac not), but when power is back the integration is not re-connecting automatically.
Meaning I've to restart home assistant to make it work again.

From my understanding it is like the integration is not retrying to reconnect.

This issue only appeared now when I move to this new branch from Wuwentao, the old one was reconnecting automatically when power was back. 

### The logs

Registrador: midealocal.device
Fuente: /usr/local/lib/python3.12/site-packages/midealocal/device.py:531
Ocurrió por primera vez: 25 de septiembre de 2024, 20:00:24 (1 ocurrencias)
Última vez registrado: 25 de septiembre de 2024, 20:00:24

[14293651214782] Socket error - Connection closed by peer

**Comment by Cotvi** [comment]
I have this problem too. York Midea heat pump

**Comment by wuwentao** [comment]
@Cotvi yes, it's a known issue in v0.5.7.
latest v0.5.9 should fix the reconnect issue and introduced some new issue, like status refresh have delay.
expected to fix it in these days.
some testing still in progress and once got confirm, will publish a new version v0.6.0 to fix all these issue.

**Comment by Cotvi** [comment]
Thx :)

czw., 26 wrz 2024, 17:09 użytkownik Hello World ***@***.***>
napisał:

**Comment by Bonabrux** [comment]
Hi @wuwentao,
Great, thanks for the feedback.
I'll we looking forward for v0.6.0

Thanks for all your work

**Comment by petepall** [comment]
> @Cotvi @Bonabrux yes, it's a known issue in v0.5.7. latest v0.5.9 should fix the reconnect issue and introduced some new issue, like status refresh have delay. expected to fix it in these days. some testing still in progress and once got confirm, will publish a new version v0.6.0 to fix all these issue after some days

Hi @wuwentao since v0.5.9 I also have that the devices are not responding until I reload the individual devices. I did not have this issue with v0.5.7

**Comment by chemelli74** [comment]
closed via #336
