### ISSUE TITLE
Slow updating the card when making changes or switch on/off

### ISSUE THREAD

**Issue by mouthpiec** [wuwentao/midea_ac_lan#331]
### HA core version

2024.09

### Current integration version

0.5.9

### Last known working integration version

0.5.7

### Device type and model

Air Conditioner 00000Q1B (44204)

### Working mobile app

na

### The description of problem

when making changes, eg switch on AC, the AC switches on, but display is updated later. before this was instant.

**Comment by wuwentao** [comment]
thanks for your bug report.
it should be fix in latest v0.6.0, once it publish, this PR will be close, please have a try.
if it still can't work for you, please update the latest result with debug log info

**Comment by mouthpiec** [comment]
confirmed - fixed with v0.6.0
