### ISSUE TITLE
Feature(Translate): 美的冰箱识别后，传感器名字为英文，如何修正为中文。

### ISSUE THREAD

**Issue by feizhenzhuang** [wuwentao/midea_ac_lan#342]
### HA版本

2024.10.0

### 集成版本

0.6.0

### 之前可正常使用的集成版本

0.4.1

### 设备类型及型号

Refrigerator 310A1649 (56)

### 使用的App

美的美居

### 问题详细描述

美的冰箱识别并加入HA后，添加传感器状态，显示全部为英文，但是在代码包中发现有[CA_hans.md](https://github.com/georgezhao2010/midea_ac_lan/blob/master/doc/CA_hans.md?plain=1)中文翻译，请问如何让ha传感器状态显示为中文呢？
![屏幕截图 2024-10-05 220417](https://github.com/user-attachments/assets/b0ef31fe-d722-48f8-a1db-fb5e527d639d)

**Comment by wuwentao** [comment]
这个比较简单，翻译问题，但是需要有对应的设备去识别美的美居app上用的什么中文名字可能才翻译的更准确， 因此目前默认使用了英文。
可以尝试修改这里对应的文字即可：
https://github.com/wuwentao/midea_ac_lan/tree/master/custom_components/midea_ac_lan/translations

目前有部分设备有中文，其他设备就是逐步完善修改，详情可参考：
https://github.com/wuwentao/midea_ac_lan/pull/294

如果不会修改的话，随后晚些抽空再提交一些翻译吧，目前还在处理一些bug，所以类似的功能没有特别去做处理，等有时间再抽空添加也行。
或者你先本地修改，确认和官方app一致了，也可以提交MR协助完成。

**Comment by wuwentao** [comment]
已提交所有翻译:https://github.com/wuwentao/midea_ac_lan/pull/353
这个PR Merge以后，你这个issue会关闭，不过下一个release就可用了。
如有翻译错误或者不准确的地方，随后再做微调

**Comment by feizhenzhuang** [comment]
谢谢您的贡献!
