### ISSUE TITLE
热水器突然不支持开关功能了

### ISSUE THREAD

**Issue by veryweak** [wuwentao/midea_ac_lan#370]
### 集成版本

0.6.5

### 之前可正常使用的集成版本

忘记了

### 设备类型及型号

Electric Water Heater 51022BA3 (255)

### 使用的App

美的美居

### 问题/Bug详细描述

Entity water_heater.211106239783636_water_heater does not support this service.

**Comment by chemelli74** [comment]
Please enable [debug](https://www.home-assistant.io/docs/configuration/troubleshooting/#enabling-debug-logging) for **Midea AC LAN** integration, wait for this error, disable debug and attach the log.

Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

Thanks

**Comment by veryweak** [comment]
[home-assistant_midea_ac_lan_2024-10-21T01-32-59.484Z.log](https://github.com/user-attachments/files/17452906/home-assistant_midea_ac_lan_2024-10-21T01-32-59.484Z.log)

**Comment by veryweak** [comment]
![image](https://github.com/user-attachments/assets/52dc67ca-8bc6-4330-b101-af245cf078a2)

I think the problem is that there are no entities of switching the heater.

**Comment by veryweak** [comment]
![image](https://github.com/user-attachments/assets/8b0ffb7c-6860-4b32-addc-bcfb5dc33fe4)

I added two scripts to switch it, but when I run the scripts, the error occurs.

![image](https://github.com/user-attachments/assets/c63212af-86d9-483e-a1b2-5fa1b55ab612)

But the error is not in log.

**Comment by wuwentao** [comment]
you may did some error action in your HA device.
try to remove this device from midea_ac_lan and remove midea_ac_lan from HA.
remove `rm -rf /config/.storage/midea_ac_lan` in your HA ssh shell

once it done, do a fresh install with midea_ac_lan and add this device again.
confirm the result again.

**Comment by veryweak** [comment]
I did what you said. But all same again. I think it is because the heater is updated by Midea, because now even when I manually turn off the heater, I need to push the button two times.

**Comment by wuwentao** [comment]
is this possible for you to join our [Discord Chat](https://discord.com/invite/ZWdd2fXndn) ?
then we can quickly confirm with the error detail

**Comment by wuwentao** [comment]
@veryweak  I have send your detail via discord, seems you always offline.
there is no any updates for a long time.
please check and confirm, thanks

**Comment by wuwentao** [comment]
> @veryweak I have send your a private msg via discord, seems your discord account always offline, and there is no any updates for a long time. please check and confirm, thanks

**Comment by wuwentao** [comment]
sorry, there is no any response for a long time, and I will close current issue.
if current issue still exist in your device, you can provide the detail log and info, and reopen current issue.
thanks

**Comment by veryweak** [comment]
Sorry I haven't responded to this issue for a long time... But the problem still exists. How can I fix it?

**Comment by wuwentao** [comment]
@veryweak 
1. please remove or disable your script, try to make sure the basic func can works well.
2. I don't got any error detail with current midea_ac_lan from your debug log, and only can found your scipt error log.
3. contact via discord chat, we can quickly sync the detail and error reason, you should keep your discord online to send or recv message.
