### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by clbx** [wuwentao/midea_ac_lan#373]
### HA版本

2024.10.2

### 集成版本

I don't read Chinese

### 之前可正常使用的集成版本

I don't read Chinese

### 设备类型及型号

Midea Cube Dehumidier

### 使用的App

I don't read Chinese

### 问题/Bug详细描述

Whenever I try and add the integration using the newest version of the integration I get the following bug: 

```
2024-10-26 02:10:21.749 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: No module named 'midealocal'
```

**Comment by chemelli74** [comment]
@clbx please use the English template and full fill all data.

**Comment by clbx** [comment]
Must have missed that, I’ll open a new one with that template.
