### ISSUE TITLE
Error starting integration "No module named 'midealocal'"

### ISSUE THREAD

**Issue by clbx** [wuwentao/midea_ac_lan#378]
### HA core version

2024.10.2

### Current integration version

0.6.5

### Last known working integration version

n/a

### Device type and model

Unsure - Midea 35L Cube Dehumidifier 

### Working mobile app

MideaAir

### The detail description of bug/problem

1. description the device type and name（you may have multiple devices）
Midea 35L Cube Dehumidfier 
2. description the error action or error info (device have multiple data/features)
When trying to add the integration to home assistant I get this error:

![image](https://github.com/user-attachments/assets/330390eb-8156-421c-a8fb-262ba3406d5f)

And this in the logs
```
2024-10-30 05:09:06.727 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration midea_ac_lan: No module named 'midealocal'
```

[homeassistant-0.log](https://github.com/user-attachments/files/17566379/homeassistant-0.log)

It appears that there are missing dependencies. I am using the container version of Home Assistant. I did not have this issue on the original integration https://github.com/georgezhao2010/midea_ac_lan when I used it a few months ago

This is caused by the midea-local python package not being included with this, I guess it was previously? 
If I run ``pip install midea-local`` in the container, the integration works. Since its running in a container, the integration will break after a restart.  I don't know a lot about how HA handles python packages, but it's my understanding the integration should pull any dependencies. 

Thanks

### The logs

1. DEBUG log MUST be enabled (Please refer to README document)
2. Execute the action to trigger error log（you should description the error action）
3. Upload the debug log file as attachment。
4. Please don't paste the log content! upload as a attachment file.
5. Please don't paste the log content! upload as a attachment file.
6. Please don't paste the log content! upload as a attachment file.
...

**Comment by chemelli74** [comment]
As you can see, it's included:

https://github.com/wuwentao/midea_ac_lan/blob/0c78e0bc98d66ef9eba84462d2bcc5e75f011929/custom_components/midea_ac_lan/manifest.json#L12

So we need to understand why it's not installed on your environment.

**Comment by clbx** [comment]
hmm yeah, I'm starting to think this might be an error with my HA Instance or HACS as opposed to this integration. I'm running into the same issue with other integrations. Going to close this unless I find something thats specific to this integration.

**Comment by clbx** [comment]
Looks like there's a open issue with HA Core where python deps are not being pulled in containerized versions of HA not running in docker: 

https://github.com/home-assistant/core/issues/127966
