### ISSUE TITLE
Comfee D80-15EFG Water Heater missing lot of entities

### ISSUE THREAD

**Issue by papperone** [wuwentao/midea_ac_lan#388]
### Device type and model (or SN)

Electric Water Heater 510003C8 (255)

### The detail description of new feature

1. support new device : no
2. support new feature: 
my water heater when integrates with this component exposes only the water temperature, I miss the ON/OFF entitiy and the switches to turn on or off specific features (Memo-U, Mega Water and Sterilization) that are available in the SmartHome official app
4. others: no

**Comment by wuwentao** [comment]
please confirm your really follow the readme docs for these setting:


Extra sensor and switch entities

After configuration, one of few main entity (e.g. climate entity) may be generated . If you want to make the attributes to extra sensor and switch entities, click CONFIGURE in Midea AC LAN integration card to choose (if your devices supported).
