### ISSUE TITLE
Can't log in to Midea (global?) to add new AC

### ISSUE THREAD

**Issue by ogghi** [wuwentao/midea_ac_lan#389]
### HA core version

2024.11.2

### Current integration version

0.6.5

### Last known working integration version

0.6.5

### Device type and model

Air condictioner 152832116911193

### Working mobile app

SmartHome

### The detail description of bug/problem

Hi, I would like to add the AC to HA as well (dishwasher working fine)
What I actually miss is where to find the login data for the cloud login to do initial setup?

Midea.com? 

Thanks :)

### The logs

1. DEBUG log MUST be enabled (Please refer to README document)
2. Execute the action to trigger error log（you should description the error action）
3. Upload the debug log file as attachment。
4. Please don't paste the log content! upload as a attachment file.
5. Please don't paste the log content! upload as a attachment file.
6. Please don't paste the log content! upload as a attachment file.
...

**Comment by wuwentao** [comment]
the web UI should show you the info,as you need to select which cloud you are using, then you need to input this cloud service that you selected.

for example, if you select SmartHome, you should using your SmartHome app account/password to do login.

in addition, if you still have login issue, please follow the README document and enable debug log.
or reboot your HA and retry again to confirm.

as you input a invalid github issue, no any detail info and no any debug log, so I will close this ISSUE.

if you still want to fix your issue, please add all the details and follow the github issue template.
anyway, you still can continue update your result in this issue after state is closed, and we will also monitor it.

thanks, please follow github issue template.

**Comment by ogghi** [comment]
Hi @wuwentao 
Sorry for not following the procedure here!

I did not know there were different clouds.
Also it seems that the password I had saved in my password manager did not match what I've set for the SmartHome cloud...so reset worked :+1: 

Thanks again for your work!

Enjoy your day
