### ISSUE TITLE
天然气热水器在家庭app不能正常工作

### ISSUE THREAD

**Issue by 2ddv** [wuwentao/midea_ac_lan#400]
### HA版本

2024.10.1

### 集成版本

0.5.7

### 之前可正常使用的集成版本

0.0.0

### 设备类型及型号

JSQ30-MK3/JSQ25-MK3

### 使用的App

美的美居

### 问题/Bug详细描述

在ha调整目标温度，家庭app中目标温度没变化；
在家庭app调整目标温度，ha中可以实时变化；
ha中的当前温度，在家庭app在没变化（除了刚添加时）

### The logs

[home-assistant_midea_ac_lan_2024-11-27T03-58-10.109Z.log](https://github.com/user-attachments/files/17928893/home-assistant_midea_ac_lan_2024-11-27T03-58-10.109Z.log)

**Comment by wuwentao** [comment]
温度同步或者刷新的频率问题？这个问题可能比较尴尬了，确实没有太多经验，大概率属于homeassiant平台的功能或者问题。
因为当前integration基本上并未做任何homekit方面的处理，全靠HA自身的homekit bridge自身实现的。
