### ISSUE TITLE
Feature(ED): support Midea Water Purifier JL2245T

### ISSUE THREAD

**Issue by polysa** [wuwentao/midea_ac_lan#402]
### Device type and model (or SN)

> The model can be found in Settings -> Devices & Services -> Midea AC LAN -> Devices -> Device Info> The SN can be found in Settings -> Devices & Services -> Midea AC LAN -> Add device -> Just list appliances> The SN also can be found in your SmartHome APP

### The detail description of new feature

Hello can we have support for Midea Water Purifier JL2245T

1. support new device : Midea Water Purifier JL2245T
2. support new feature: From the app we have Water Cosumption, Water Valume Selection (3 Valumes), Water Temperature (Hot & Cold), Eco Mode, Hot Water Sterilization, PAC Filter (Remaining & and days), C+UF Filter (Remaining % and days)

Appliance code: 152832116925069
Type: ED
SN: 0000ED54163100005450721003131PFF
Supported: Yes

**Comment by wuwentao** [comment]
ED device is already supported,  could you help to confirm with the details?

https://github.com/wuwentao/midea_ac_lan/blob/master/doc/ED.md

**Comment by wuwentao** [comment]
@polysa 
there is a device subtype for different product, and I'm not sure with your device subtype, as you don't provide me the full debug log in your issue.

maybe you can directly edit the source code and confirm the result. 
if it still can't works for you, you can upload the detail debug log and we can do future check.

how to manual edit it:
you just need to change one line :
https://github.com/midea-lan/midea-local/blob/22462e68d8cc776f5c09d9b3bfea97e595701587/midealocal/devices/ed/message.py#L49

```
body_type: ListTypes = ListTypes.X00,
```

the last content is `ListTypes.X00`, you should replace `X00` with [`X01`  , or `X03`,  or `X04`, or `X05` or `X06` or `X07`  or `FF` **(NOT XFF, it's FF)**]  to test it(replace the default value), and confirm which VALUE can works for your device and got a expected respone.
then we can add it later.

in addition,  **if your changes this value everytime, you should reboot HA to take effect.**
so just enable debug log via configuration.yaml and you can got all the details after device reboot done.

it's not a finally solution and just a quickly debug/test solution, and I will try to commit it once got confirm with you.
thanks


how to change it, below is the detail steps:

1. if you are using HAOS, you should install Add-on [Advanced SSH & Web Terminal] and disable [Protected Mode], once it done, you can ssh to your HAOS, and enter docker in HAOS `docker exec -it homeassistant /bin/bash`, contiune the step to check `midea-local` install path
2. if you not using HAOS, just check `midea-local` install path as the next step
3. get `midea-local` install path with command `pip show midea-local`, it will show info for you, for example, my location is `Location: /usr/local/lib/python3.12/site-packages`
4. then we can edit the file `/usr/local/lib/python3.12/site-packages/midealocal/devices/ed/message.py` with the  code changes, using vi command line tool or any method you can do it. 
 5. reboot HA and test with it, confirm with the result or debug log.

**Comment by wuwentao** [comment]
in addition, there is a same github issue with ED device:
https://github.com/wuwentao/midea_ac_lan/issues/352

and I have submit a fix for this device, you can also confirm with it.

**Comment by polysa** [comment]
How can i provide the full debug log?

**Comment by wuwentao** [comment]
@polysa  any updates for your test result ?

**Comment by polysa** [comment]
Hello
Sorry for the late responce 
It's working now without altering the code. Maybe you pushed an update to include this?

The only thing missing are the Filters Remaining days 

I dont know if they are available from the api but we can calculate them based the percentage of the 2 filters like this:

filter 1 remaining days = 96% * 360 = 345.6 days rounded to 346 days
filter 2 remaining days = 96% * 360 = 345.6 days rounded to 346 days

![image](https://github.com/user-attachments/assets/a95fe6b3-cf9c-4ca1-a79c-e988acf2723a)

**Comment by wuwentao** [comment]
@polysa there is no any updates.
so I just think there is some error caused your device and HA connection broken, and it can't works.
you may reboot your HA and it recovery to normal status.
you can continue check it and confirm the result.


for the filter life and available days, it should based on your device type and app result.
anyway, we still need debug log to confirm it.
so you can add it to configuration.yaml and got the full debug log after HA reboot.

**Comment by wuwentao** [comment]
below is your debug log output 
```
2024-12-16 09:02:28.912 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Does not supports the protocol MessageQuery, cmd {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query: 3>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, 'header': 'aa0ced00000000000003', 'body': '0001', 'message_type': 'query', 'body_type': '00', 'self': <midealocal.devices.ed.message.MessageQuery object at 0x7fa7e77d6cf0>}, ignored

```


the output using default X00, and exist PR https://github.com/midea-lan/midea-local/pull/328 add a new query X01, so you  can use this X00 and X01 to confirm with your device, if it can works for your device, you don't need to test more value.
if X00 and X01 can't works for your device, you can manual change the value, test with [`X01` , or `X03`, or `X04`, or `X05` or `X06` or `X07` or `FF` **(NOT XFF, it's FF)**]
confirm which one can works for your device, if it works, you will got a response from your device or got a `Unidentified protocol` output, but NOT `Does not supports the protocol` and `unsupported protocol, SKIP`.


so  we need to confirm which query value can works for your ED device, you have this device, so you should follow this test step to confirm it(I can't test it for you).

you can also refer to this issue test steps(understand how to test and chagne code for your device test):
https://github.com/wuwentao/midea_ac_lan/issues/404#issuecomment-2550966152


below is the test for your device that I have posted in previous reply :

> @polysa there is a device subtype for different product, and I'm not sure with your device subtype, as you don't provide me the full debug log in your issue.
> 
> maybe you can directly edit the source code and confirm the result. if it still can't works for you, you can upload the detail debug log and we can do future check.
> 
> how to manual edit it: you just need to change one line : https://github.com/midea-lan/midea-local/blob/22462e68d8cc776f5c09d9b3bfea97e595701587/midealocal/devices/ed/message.py#L49
> 
> ```
> body_type: ListTypes = ListTypes.X00,
> ```
> 
> the last content is `ListTypes.X00`, you should replace `X00` with [`X01` , or `X03`, or `X04`, or `X05` or `X06` or `X07` or `FF` **(NOT XFF, it's FF)**] to test it(replace the default value), and confirm which VALUE can works for your device and got a expected respone. then we can add it later.
> 
> in addition, **if your changes this value everytime, you should reboot HA to take effect.** so just enable debug log via configuration.yaml and you can got all the details after device reboot done.
> 
> it's not a finally solution and just a quickly debug/test solution, and I will try to commit it once got confirm with you. thanks
> 
> how to change it, below is the detail steps:
> 
> 1. if you are using HAOS, you should install Add-on [Advanced SSH & Web Terminal] and disable [Protected Mode], once it done, you can ssh to your HAOS, and enter docker in HAOS `docker exec -it homeassistant /bin/bash`, contiune the step to check `midea-local` install path
> 2. if you not using HAOS, just check `midea-local` install path as the next step
> 3. get `midea-local` install path with command `pip show midea-local`, it will show info for you, for example, my location is `Location: /usr/local/lib/python3.12/site-packages`
> 4. then we can edit the file `/usr/local/lib/python3.12/site-packages/midealocal/devices/ed/message.py` with the  code changes, using vi command line tool or any method you can do it.
> 5. reboot HA and test with it, confirm with the result or debug log.

**Comment by polysa** [comment]
Hello i Tested this with all suggested ListyTypes X01, X03, X04, X05, X06, X07 and XFF. The only one worked for some minutes and the failed is the X01. When the device is unavailable the Home Assistant is not stable keeps disconnecting and failing. 

Also for all Listtypes i get the same log entry:

`2024-12-20 11:08:14.024 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Sending: {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query_appliance: 160>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, 'header': 'aa1ded000000000000a0', 'body': '00000000000000000000000000000000000000', 'message_type': 'query_appliance', 'body_type': '00', 'self': <midealocal.message.MessageQueryAppliance object at 0x7f92c1641e00>}, query is True
`

**Comment by wuwentao** [comment]
@polysa  sorry,you don't upload any debug log file, I can't confirm with your descrption.
as you just posting a uncessary debug log info with a `MessageQueryAppliance `. 
what we need it `MessageQuery` with different type.

**Comment by polysa** [comment]
Log uploaded

![image](https://github.com/user-attachments/assets/e7651371-86bc-4de5-9a57-46bf512e174b)


[home-assistant_midea_ac_lan_2024-12-23T09-51-26.130Z.log](https://github.com/user-attachments/files/18228002/home-assistant_midea_ac_lan_2024-12-23T09-51-26.130Z.log)

**Comment by wuwentao** [comment]
@polysa  sorry, I don't think you have follow the manual test steps.
you degbu log always showing old X00 value.
```
2024-12-23 11:51:01.537 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] refresh_status with cmds: [<midealocal.message.MessageQueryAppliance object at 0x7fec6c79f820>, <midealocal.devices.ed.message.MessageQuery object at 0x7fec6e7abb60>], check_protocol True
2024-12-23 11:51:01.537 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Sending: {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query_appliance: 160>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, 'header': 'aa1ded000000000000a0', 'body': '00000000000000000000000000000000000000', 'message_type': 'query_appliance', 'body_type': '00', 'self': <midealocal.message.MessageQueryAppliance object at 0x7fec6c79f820>}, query is True
2024-12-23 11:51:01.706 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Appliance query Received: {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query_appliance: 160>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, '_header': 'aa2aed000000000000a0', '_body': <midealocal.message.MessageBody object at 0x7fec6c6d48f0>, 'header': 'aa2aed000000000000a0', 'body': '00ed4d0300000000000000000000000000000000000000000000000000000000', 'message_type': 'query_appliance', 'body_type': '00', 'self': <midealocal.message.MessageApplianceResponse object at 0x7fec5c39d0f0>}
2024-12-23 11:51:01.706 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Device protocol version: 0
2024-12-23 11:51:01.706 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Sending: {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query: 3>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, 'header': 'aa0ced00000000000003', 'body': '0001', 'message_type': 'query', 'body_type': '00', 'self': <midealocal.devices.ed.message.MessageQuery object at 0x7fec6e7abb60>}, query is True
2024-12-23 11:51:03.709 DEBUG (Water Dispenser ) [midealocal.device] [152832116925069] Does not supports the protocol MessageQuery, cmd {'_device_type': <DeviceType.ED: 237>, '_message_type': <MessageType.query: 3>, '_body_type': <ListTypes.X00: 0>, '_message_protocol_version': 0, 'header': 'aa0ced00000000000003', 'body': '0001', 'message_type': 'query', 'body_type': '00', 'self': <midealocal.devices.ed.message.MessageQuery object at 0x7fec6e7abb60>}, ignored
```

`ListTypes.X00: 0`
you should reboot after you have changed the source code.

if it's hard for you to do, and you can't finish this test by yourself, I will pause this discuss and progress,  you can just wait for future new release update.
**once new release published(you should wait for some days,.I'm not sure now)**, just update to latest version and provide the full debug log,  and I will try to find out the error for your device.
