### ISSUE TITLE
美的空调咋把显示的温度改成摄氏度显示？

### ISSUE THREAD

**Issue by xsj520** [wuwentao/midea_ac_lan#406]
<img width="263" alt="屏幕截图 2024-12-01 212117" src="https://github.com/user-attachments/assets/56e2e78f-f0c9-498d-b249-f068117c6b66">
美的空调添加好以后显示的是华氏度（℉），咋改成摄氏度（­°C）啊。
<img width="263" alt="屏幕截图 2024-12-01 212117" src="https://github.com/user-attachments/assets/56e2e78f-f0c9-498d-b249-f068117c6b66">

**Comment by wuwentao** [comment]
抱歉，这是您HA 的设置问题，跟当前integration没有任何关系。
请登录HA web，设置，通用，单位，自行修改，谢谢
