### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by Daeloran** [wuwentao/midea_ac_lan#410]
### HA core version

2024.12.1

### Current integration version

0.6.5

### Last known working integration version

none

### Device type and model

Midea Air conditionner

### Working mobile app

Smarthome

### The detail description of bug/problem

My issue is at the authentication part. 
I've create my SmartHome app account with my google account. I don't know if it can be an issue here.
I've change my password in the application to be sure of it but it seems to not change anything. I use my mail address as login.

### The logs

Failed to login, account or password was wrong

**Comment by wuwentao** [comment]
@Daeloran  please follow the README document to enable debug log and upload to github issue as attachment
required full debug log file, NOT a part of the debug log, thanks.

without debug log, we can do nothing for current issue,sorry

**Comment by Daeloran** [comment]
Like I supposed, the issue come from the fact I've created my Smarthome account using the Google connection. After recreate another account with an email adress, it was working fine. Just a bit painful to have to redo configuration on another account.

Thanks
