### ISSUE TITLE
Bug(E2):Electric Water Heater 510003BH - whole tank heating not work

### ISSUE THREAD

**Issue by CesarAmores** [wuwentao/midea_ac_lan#412]
### Current integration version

0.6.5

### Last known working integration version

0.6.5

### Device type and model

water heater 510003BH

### Working mobile app

SmartHome

### The detail description of bug/problem

1. I have only one device, the water heater, which is correctly configured by the UI mode model : 510003BHby E2.md
2.  The functionalities to change the temperature and turn the device off work, but the one that should modify the "Whole Tank Heating" value to false or true doesn't work. When I try to change the switch, it always returns to its initial condition.

Update all data. plz help meee
[home-assistant_midea_ac_lan_2024-12-08T12-12-49.857Z.log](https://github.com/user-attachments/files/18051981/home-assistant_midea_ac_lan_2024-12-08T12-12-49.857Z.log)
[config_entry-midea_ac_lan-01JDT8R43Q5DJX2X4FTFQMRK8H (3).json](https://github.com/user-attachments/files/18051983/config_entry-midea_ac_lan-01JDT8R43Q5DJX2X4FTFQMRK8H.3.json)

### The logs

1. DEBUG log MUST be enabled (Please refer to README document)
2. Execute the action to trigger error log（you should description the error action）
3. Upload the debug log file as attachment。
4. Please don't paste the log content! upload as a attachment file.
5. Please don't paste the log content! upload as a attachment file.
6. Please don't paste the log content! upload as a attachment file.
...

**Comment by wuwentao** [comment]
@CesarAmores from your debug log, I found the first error is  `2024-12-08 12:50:10.724 ERROR (MainThread) [midealocal.devices.e2] [153931628312717] Set customize error
`
so you should enabled customize , and seems this setting have error and not works anymore, 
please doulbe check with your customize setting and copy/paste it from E2 doc, try to make sure it can works well and without error, then control your device with both old_protocol is tue or false or remove it with default auto.

`{ "old_protocol": true }`

`{ "old_protocol": false }`

`{ "old_protocol": auto }`

or remove it and keep default value if `Set customize error` error still exist.

if error still exist, provide your debug log without `Set customize error`

**Comment by wuwentao** [comment]
@CesarAmores any updates with these changes?

**Comment by wuwentao** [comment]
@CesarAmores if threre is no any update for a long time, I will consider to close it as issue not exist.

**Comment by CesarAmores** [comment]
Hi,
Sorry for the time that has passed.
Here are the logs with the various protocols I’ve tried.

With :
![image](https://github.com/user-attachments/assets/fb9b8ae8-7267-415c-a4f9-401c64185f92)

[home-assistant_midea_ac_lan_2024-12-29T16-31-57.706Z.log](https://github.com/user-attachments/files/18270260/home-assistant_midea_ac_lan_2024-12-29T16-31-57.706Z.log)


But is working now with
![image](https://github.com/user-attachments/assets/93f95d90-bc93-47a5-9946-cfbbb6738637)

Many thaks
