### ISSUE TITLE
Feature(ED): 美的净水机（MRO820-R）添加后无实体，通过扩展添加后无状态显示不可用

### ISSUE THREAD

**Issue by lihdmi-3** [wuwentao/midea_ac_lan#424]
### HA版本

2024.12.4

### 集成版本

v0.6.5

### 之前可正常使用的集成版本

无

### 设备类型及型号

Water Drinking Appliance 632009C6 (987)

### 使用的App

美的美居

### 问题/Bug详细描述

美的净水机（MRO820-R）添加后无实体，通过扩展添加后无状态显示不可用

### The logs

[
![Uploading 屏幕截图 2024-12-23 082605.png…]()
](url)

**Comment by lihdmi-3** [comment]
![屏幕截图 2024-12-23 082605](https://github.com/user-attachments/assets/fc86e4ab-ae01-4aef-b2e2-200771315fa3)

**Comment by wuwentao** [comment]
@lihdmi-3 首先，还是需要按issue template提供必要的debug log。

其次，请直接参考已有issue和解决办法：
https://github.com/wuwentao/midea_ac_lan/issues/352
如果这个不行，可以参考：
https://github.com/wuwentao/midea_ac_lan/issues/402

帮忙尽快给个测试结果确认，应该是类似问题，可以一并解决，但是不同的设备具体使用哪个值，可能需要您自行测试和确认。
如果操作太复杂，不会测试，那就等随后发布新版，再提交debug log即可。
