### ISSUE TITLE
[152832116461697] Socket error - Connection closed by peer

### ISSUE THREAD

**Issue by Dino0005** [wuwentao/midea_ac_lan#49]
### HA core version

2024.5.5

### Integration version

v0.4.0 (even if in the manifest.json file the version reported is v0.4.0-alpha)

### Device type and model

Air Conditioner 00000Q18 (44204)

### Used App

MSartHome and Home Assistant

### The description of problem

Registratore: midealocal.device
Fonte: /usr/local/lib/python3.12/site-packages/midealocal/device.py:397
Prima occorrenza: 11:47:39 (1 occorrenze)
Ultima registrazione: 11:47:39

[152832116461697] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 378, Exception('not an 8370 message')

the same error also occurred with previous versions of Midea AC Lan, which I reported here:
[https://github.com/CyrielRct/midea_ac_lan/issues/8#issue-2278947288](url)

### The logs

2024-05-31 11:47:39.529 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Unknown error :/usr/local/lib/python3.12/site-packages/midealocal/device.py, 378, Exception('not an 8370 message')

[home-assistant_midea_ac_lan_2024-05-31T17-03-43.741Z.log](https://github.com/user-attachments/files/15516773/home-assistant_midea_ac_lan_2024-05-31T17-03-43.741Z.log)

**Comment by rokam** [comment]
It looks like it is expecting a v3 message but receiving another protocol type.  Is your AC a v3 one? How have you configured it? By discover?

**Comment by Dino0005** [comment]
After adding it to MSartHome, I added it to Home Assistant with "Automatically Discover" option (Midea AC LAN v.0.3.22)

**Comment by chemelli74** [comment]
Hi @Dino0005 , can you please update to latest and report back if the error is still there ?

**Comment by Xeyrruken** [comment]
> Hi @Dino0005 , can you please update to latest and report back if the error is still there ?

I'm having the same issue on the latest build.

**Comment by chemelli74** [comment]
Please attach a fresh debug log

**Comment by Xeyrruken** [comment]
> Please attach a fresh debug log

I'm trying to add a new device.

` File "/config/custom_components/midea_ac_lan/config_flow.py", line 478, in async_step_manually
    self._save_device_config(data)
  File "/config/custom_components/midea_ac_lan/config_flow.py", line 128, in _save_device_config
    record_file = Path(storage_path, data[CONF_DEVICE_ID], ".json")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by wuwentao** [comment]
> > Please attach a fresh debug log
> 
> I'm trying to add a new device. With auto discovery function.
> 
> ` File "/config/custom_components/midea_ac_lan/config_flow.py", line 478, in async_step_manually self._save_device_config(data) File "/config/custom_components/midea_ac_lan/config_flow.py", line 128, in _save_device_config record_file = Path(storage_path, data[CONF_DEVICE_ID], ".json") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`


thanks, it's a known issue for add a new device .
we have fixed it.
Is this possible for you to clone current repo and copy all the file under `custom_components/midea_ac_lan/`

to your HA install path:
`/config/custom_components/midea_ac_lan/`

once file replaced, reboot your HA and it should works.

it only can fix add new device error, and you still need to provide the debug log for your device error.

for how to enable debug log, please refer to [DEBUG](https://github.com/wuwentao/midea_ac_lan?tab=readme-ov-file#debug) setting in the end of README.

**Comment by Dino0005** [comment]
> Hi @Dino0005 , can you please update to latest and report back if the error is still there ?


with version v0.4.2, after restarting Home Assistant, these are the logs
````
2024-06-25 20:55:29.198 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-06-26 01:56:09.021 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 522
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 522, in run
result = self.parse_message(msg)
^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 339, in parse_message
messages, self._buffer = self._security.decode_8370(self._buffer + msg)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/midealocal/security.py", line 338, in decode_8370
raise MessageWrongFormat("not an 8370 message")
midealocal.exceptions.MessageWrongFormat: not an 8370 message
2024-06-26 14:00:56.786 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Socket error - Connection closed by peer
````

**Comment by wuwentao** [comment]
> > Hi @Dino0005 , can you please update to latest and report back if the error is still there ?
> 
> with version v0.4.2, after restarting Home Assistant, these are the logs
> 
> ```
> 2024-06-25 20:55:29.198 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2024-06-26 01:56:09.021 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 522
> Traceback (most recent call last):
> File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 522, in run
> result = self.parse_message(msg)
> ^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 339, in parse_message
> messages, self._buffer = self._security.decode_8370(self._buffer + msg)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/midealocal/security.py", line 338, in decode_8370
> raise MessageWrongFormat("not an 8370 message")
> midealocal.exceptions.MessageWrongFormat: not an 8370 message
> 2024-06-26 14:00:56.786 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Socket error - Connection closed by peer
> ```

thanks, seems the message is error, and not include the original message info, so this is not enough.
you should download your log file and attach it to current issue. 
we can check with the message content and detail error with the full log file.

**Comment by Dino0005** [comment]
> > > Hi @Dino0005 , can you please update to latest and report back if the error is still there ?
> > 
> > 
> > with version v0.4.2, after restarting Home Assistant, these are the logs
> > ```
> > 2024-06-25 20:55:29.198 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> > 2024-06-26 01:56:09.021 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Unknown error : /usr/local/lib/python3.12/site-packages/midealocal/device.py, 522
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 522, in run
> > result = self.parse_message(msg)
> > ^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.12/site-packages/midealocal/device.py", line 339, in parse_message
> > messages, self._buffer = self._security.decode_8370(self._buffer + msg)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "/usr/local/lib/python3.12/site-packages/midealocal/security.py", line 338, in decode_8370
> > raise MessageWrongFormat("not an 8370 message")
> > midealocal.exceptions.MessageWrongFormat: not an 8370 message
> > 2024-06-26 14:00:56.786 ERROR (AC Tavernetta) [midealocal.device] [152832116461697] Socket error - Connection closed by peer
> > ```
> 
> thanks, seems the message is error, and not include the original message info, so this is not enough. you should download your log file and attach it to current issue. we can check with the message content and detail error with the full log file.

Hi @wuwentao, here is the log file
[home-assistant_midea_ac_lan_2024-06-27T07-41-07.187Z.log](https://github.com/user-attachments/files/16009972/home-assistant_midea_ac_lan_2024-06-27T07-41-07.187Z.log)

**Comment by wuwentao** [comment]
@Dino0005 
sorry, you didin't follow the debug step to enable the debug log ? or you have enabled it and not reboot your HA ?

the log is the same as previous txt info, no any debug log print.

please confirm you have enabled debug mode for both midea_ac_lan and midealocal
or you forgot to reboot it .

**Comment by Dino0005** [comment]
Since the last restart of Home Assistant it seems that it no longer has the "Unknown error", but this "Socket error - Connection closed by peer":

````
Registratore: midealocal.device
Fonte: /usr/local/lib/python3.12/site-packages/midealocal/device.py:516
Prima occorrenza: 30 giugno 2024 alle ore 15:16:28 (3 occorrenze)
Ultima registrazione: 30 giugno 2024 alle ore 15:16:49

[144036023336957] Socket error - Connection closed by peer
[146235046592188] Socket error - Connection closed by peer
[146235046592183] Socket error - Connection closed by peer
```

[home-assistant_midea_ac_lan_2024-07-01T06-46-55.939Z.log](https://github.com/user-attachments/files/16049010/home-assistant_midea_ac_lan_2024-07-01T06-46-55.939Z.log)

**Comment by chemelli74** [comment]
Hi, first the log you attached is a partial log. We need the full log to make an analysis.

Second, please disable "**solis**" as it does blocking call to open inside the event loop. This can corrupt the whole loop that is common to all integrations.

**Comment by Dino0005** [comment]
> Hi, first the log you attached is a partial log. We need the full log to make an analysis.
> 
> Second, please disable "**solis**" as it does blocking call to open inside the event loop. This can corrupt the whole loop that is common to all integrations.

the home-assistant_midea_ac_lan_2024-07-01T06-46-55.939Z.log file is what I get by disabling Midea AC LAN debug logging, I notice that it is practically the same as that of Home Assistant.


<img width="1285" alt="Screenshot 2024-07-01 alle 10 36 41" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/9b2132f8-00bb-4c43-bb59-b5bde4d96fb1">

On previous occasions I had obtained the log file from the Midea debug recording, resulting in a larger file. Now I don't know which version of Midea AC LAN I was using.....
Could it be due to the Solis custom component if the log file is not complete?

**Comment by chemelli74** [comment]
Please check with v0.4.3 and if still experience the issue, add the following to `configuration.yaml` , restart HA, and post the log:
```yaml
logger:
  default: warning
  logs:
    custom_components.midea_ac_lan: debug
    midealocal: debug
 ```
Note: it is better to drag the log into the comment (which will add it as an attachment) and not copy paste as it is hard to read logs in GitHub.

**Comment by Dino0005** [comment]
It seems that "Unknown error" is no longer there, but now there is this "Socket error - Connection closed by peer":

````
Registratore: midealocal.device
Fonte: /usr/local/lib/python3.12/site-packages/midealocal/device.py:516
Prima occorrenza: 16:05:30 (3 occorrenze)
Ultima registrazione: 16:05:57

[146235046592188] Socket error - Connection closed by peer
[144036023336957] Socket error - Connection closed by peer
[146235046592183] Socket error - Connection closed by peer
```
`
I attach the log file

[home-assistant_midea_ac_lan_2024-07-03T15-59-30.340Z.log.zip](https://github.com/user-attachments/files/16087716/home-assistant_midea_ac_lan_2024-07-03T15-59-30.340Z.log.zip)

**Comment by wuwentao** [comment]
@Dino0005  some more question:
 1. it can works well in previous verion ?  if yes, version  no?
 2. if no, and only the first time to use it, is this a v3 device? and all the device add process is sucess and without error? or you have manual update some device info and add it pass ? you can show your device config info with `cat /config/.storage/midea_ac_lan/146235046592183.json`  in HA device Terminal or SSH,  and the number `146235046592183` is your device id, another one is `144036023336957`.
 3. could you share the device config with us and your device add step?

if all the device add step is as expect without error, we may need to add more debug output to print more info for debug.

first of all, we should confirm device add job and configs, please double check with json config.

**Comment by Dino0005** [comment]
The air conditioners were added with the "Discover automatically" option, using version v0.3.22, and even in this version, it occasionally gave this "[152832116461697] Unknown error".

From version v0.4.2, I also encountered "Socket error - Connection closed by peer" but even with these errors, the air conditioners work normally and can be controlled by Home Assistant.

They are also exposed to HomeKit using HomeKit Bridge and work using voice commands with Siri.

From version v0.4.3, I no longer see "[152832116461697] Unknown error", but only "Socket error - Connection closed by peer" (which only appears a few days after restarting Home Assistant).

I have deleted and re-added the air conditioners, which are added with "Discover automatically" without errors... sharing the screenshots.

<img width="1570" alt="Screenshot 2024-07-04 alle 21 01 25" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/672f086e-8b59-47a1-bfa3-20cf96287345">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 01 33" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/824ed5e7-144f-4cb8-b4c2-87866eab3880">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 01 41" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/b4896a40-b735-4bee-916d-2d601e0e156c">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 01 55" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/5b687db2-f246-4804-9388-90bfe6d4a16d">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 02 45" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/1c4b7120-12d2-41c3-bef2-589120d0374f">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 03 56" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/65bb2c57-1334-4d8e-8512-6d0424016890">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 04 33" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/28a849d6-f58d-4e54-bfb1-fad820e7506f">

<img width="1570" alt="Screenshot 2024-07-04 alle 21 05 06" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/7aba5bb7-aef6-449d-8fbf-8910c68aea67">

**Comment by wuwentao** [comment]
thanks for your detail info and screenshot.

after remove all the old configs and readd it, there is no any error log now?
you can check and confirm it with 1-3 days, then update the result to us.

if there is still some more socket error exist, you can contact with us , and we may need to add some new debug output to check and find out the error.

**Comment by Dino0005** [comment]
No, at the moment I have no errors or warnings for the Midea integration.
I will also check in the next few days and if there are any I will report them.

**Comment by Dino0005** [comment]
today I have again "Socket error - Connection closed"

2024-07-06 14:56:46.623 ERROR (AC Ingresso) [midealocal.device] [146235046592188] Socket error - Connection closed by peer
2024-07-06 14:59:27.323 ERROR (AC Soggiorno) [midealocal.device] [146235046592183] Socket error - Connection closed by peer
2024-07-06 16:54:40.125 ERROR (AC Corridoio) [midealocal.device] [144036023336957] Socket error - Connection closed by peer

**Comment by chemelli74** [comment]
Unfortunately those errors are network errors.
They are reported if during a communication started from HA the called device stop replying.

Please check the log for a few days and probably you see small amount of recurrences and at different interval as network issues happens casually.

**Comment by wuwentao** [comment]
@Dino0005  is the error still exist these days?
and could you help to chek your network connection ttl/response time from HA? as the protocol is works in LAN, it should no more network connection issue.
or you are using any virtual LAN ? 

just `ping` your device IP from HA terimal/ssh with more packets.
the ping command will report round-trip min/avg/max, it should be 1-2 ms  or less than 1ms and 0% packet loss.

**Comment by rokam** [comment]
This looks like a network error. Some dongles stop working out of the blue, this might be the case. We should close this one as it isn't an integration error.

**Comment by Dino0005** [comment]
My local network consists of a FritzBox 7590 AX and a Fritz Repetear 1200 AX.
I had a power surge a few hours ago, which restarted my Fritzbox router, the power outage was very short and therefore did not restart Home Assistant yellow...which continued to work
Looking in the HA registry I found:
[152832116461697] Unknown error
[146235046592188] Socket error - Connection closed by peer
[144036023336957] Socket error - Connection closed by peer
[146235046592183] Socket error - Connection closed by peer

So it appears that these are network problems.
there is a disconnection of the Midea device and immediately follows the reconnection, so a user does not notice anything since the devices respond to commands.


These are the pings:

--- 192.168.178.61 ping statistics ---
26 packets transmitted, 26 packets received, 0% packet loss
round-trip min/avg/max = 4.785/5.727/7.729 ms

--- 192.168.178.27 ping statistics ---
26 packets transmitted, 26 packets received, 0% packet loss
round-trip min/avg/max = 3.556/4.763/6.393 ms

--- 192.168.178.25 ping statistics ---
28 packets transmitted, 28 packets received, 0% packet loss
round-trip min/avg/max = 0.834/1.252/2.324 ms

--- 192.168.178.26 ping statistics ---
29 packets transmitted, 29 packets received, 0% packet loss
round-trip min/avg/max = 2.508/4.661/6.702 ms

**Comment by chemelli74** [comment]
Looking at round-trip values you are experiencing some sort fo network issues.
Usually min should be 0.5ms and max 1/1.5ms

**Comment by wuwentao** [comment]
@chemelli74   @Dino0005  just confirm with my device, seems it's ok, these IoT device using 2.4G wifi and the round-trip should greater than wired connection.

one more check,  is this possible for you to manual edit the source code of midea-local in HA core?

just login to HA core and run `pip show midea-local` you will find out the lib path like `/usr/local/lib/python3.12/site-packages/midealocal/`

manual edit with `vi` or `vim` or any tools you can edit/save the file. or manual edit in your local PC and upload to HA core device .

edit content:
`device.py` in this line 557(based on your local version):
https://github.com/rokam/midea-local/blob/5ad87b5e8ecc90850124b3de1753ef08f507eeb3/midealocal/device.py#L557

search `self._socket.settimeout(1)`
and update it to `self._socket.settimeout(3)`
means change the timeout value from `1` to `3`

save file and restart HA, and monitor for some days.
to confirm there is still socket error or no any socket error exist.

please share your result with us.

**Comment by Dino0005** [comment]
I use HA OS on a Home Assistant Yellow..."pip show midea-local" doesn't work in the terminal

<img width="895" alt="Screenshot 2024-07-10 alle 17 33 21" src="https://github.com/wuwentao/midea_ac_lan/assets/167996504/623b401c-51bb-4db5-b964-767890b65ca0">

**Comment by wuwentao** [comment]
@Dino0005 HA core running as docker container in HA os
`
Settings  -->  Advanced SSH & Web Terminal  --> Protection mode  --> Disable
`
maybe neet do reboot HA ? forgot about it

then you can use `docker ps` in this terimal,  for exmaple in my HA OS:
```
~ # docker ps
CONTAINER ID   IMAGE                                                      COMMAND               CREATED         STATUS                PORTS                                   NAMES
cf5ac65ca08b   ghcr.io/home-assistant/qemux86-64-homeassistant:2024.6.4   "/init"               8 days ago      Up 14 hours                                                   homeassistant
```

got the container ID  `cf5ac65ca08b` from the output
run  `docker exec -it cf5ac65ca08b /bin/bash`
then you will login to HA core container, and you can run `pip show midea-local`
it should be `/usr/local/lib/python3.12/site-packages`, as you are using container.

change the file permission and edit it.
> if you update HA or midea_ac_lan, the changes will be lost....

**Comment by wuwentao** [comment]
close current issue as there is no any response for a long time.
if issue still exist, you can reopen current issue again, thanks
