### ISSUE TITLE
Heat pump C3 (water_heater entity) looks different than in version 0.3.22

### ISSUE THREAD

**Issue by erikgieseler** [wuwentao/midea_ac_lan#59]
### HA core version

2024.5.5

### Integration version

0.4.1

### Device type and model

C3 - Heat Pump Wi-Fi Controller 171H120F

### Used App

MSmartHome

### The description of problem

Hello, 

I have just tested version 0.4.1 with my C3 heat pump. I immediately noticed that the water_heater entity looks different compared to version 0.3.22, see attached screenshots. The color gradient for the temperatures is no longer displayed.

0.3.22
![0 3 22 4](https://github.com/wuwentao/midea_ac_lan/assets/72557610/62ac489f-2da0-4f1b-9045-2af7df1e39d0)

0.4.1
![0 4 1](https://github.com/wuwentao/midea_ac_lan/assets/72557610/3bf9ba0d-5a4a-4d27-b7a8-57cc6e77ef13)

**Comment by chemelli74** [comment]
Thx for the report.
A couple of questions:

- Is everything else working as expected ?

- anything reported in the log ?

**Comment by erikgieseler** [comment]
Unfortunately there is nothing in the log (debug level).
Everything else works as it should.

**Comment by erikgieseler** [comment]
There are errors in the log. I didn't see them at first.
[C3.log](https://github.com/user-attachments/files/15526014/C3.log)

**Comment by wuwentao** [comment]
oh, seems PR merge auto close this issue, could you help to check and confirm whether it can works ?
temp reopen it and got confirm with issue owner, we can close it later, sorry

**Comment by erikgieseler** [comment]
The modification works with my C3 heat pump.
Thank you!

**Comment by chemelli74** [comment]
IF everything works as expected, please close this issue.
