### ISSUE TITLE
请求添加小天鹅蓝洋二代洗衣机和干衣机套装

### ISSUE THREAD

**Issue by invoker-karl** [wuwentao/midea_ac_lan#6]
### 设备类型及型号 (或SN)

小天鹅蓝氧二代洗衣机和干衣机

### 新功能的描述

小天鹅干衣机-蓝氧二代
设备型号：211106239178619
类型：DC
SN：0000DC513382078213B165AXXXXXXXXXX

小天鹅洗衣机-蓝氧二代
设备型号：208907215418186
SN：0000DB5133812992941025XXXXXXXXXX

并且请求支持这两个设备对于用电量的支持（美的美居里可以看到）。

目前Midea AC LAN 可以搜索到设备，且显示支持，但是在插件里连接的时候提示无法连接到指定设备。

**Comment by wuwentao** [comment]
感谢反馈
目前应该刚把repo fork过来，还有不少问题需要解决，新功能和这种估计会晚一些根据时间再看看。
最好是其他小伙伴们，有这类设备的，也方便测试和验证，可以帮忙提PR来一起支持。

**Comment by invoker-karl** [comment]
好的！感谢提供帮助！ 支持！

**Comment by wuwentao** [comment]
请安装首页readme开启debug log，然后添加设备，出错以后，将debug log上传上来，看看报错的地方在哪里。
@invoker-karl

**Comment by invoker-karl** [comment]
[home-assistant_2024-07-03T15-44-34.661Z.log](https://github.com/user-attachments/files/16087449/home-assistant_2024-07-03T15-44-34.661Z.log)
请查收日志。

**Comment by invoker-karl** [comment]
通过对最新版本0.4.3的更新，小天鹅干衣机已经可以加入到HA中，不能加入的是小天鹅洗衣机。

**Comment by wuwentao** [comment]
> 通过对最新版本0.4.3的更新，小天鹅干衣机已经可以加入到HA中，不能加入的是小天鹅洗衣机。

感谢反馈，目前是设备auth failed，随后修改一些信息，再次尝试看看吧，下个版本吧。

**Comment by invoker-karl** [comment]
好的！ 辛苦！ 谢谢！

**Comment by rokam** [comment]
Can you please try v0.5.0?

**Comment by wuwentao** [comment]
@invoker-karl 请升级最新的v0.5.0，并按首页readme最后一段的说明，开启midea_ac_lan和midealocal的debug log，重启HA，再执行添加设备的操作，不管成功与否，帮忙上传一份debug log，主要方便对比小天鹅洗衣机添加的数据，目前有不少无法添加成功的数据，希望能够对比一下成功和失败的设备返回的具体软硬件版本信息。

**Comment by invoker-karl** [comment]
还是不行。这次显示Can't get available token for this device。 
下面附上调试日志。请查收。
[home-assistant_midea_ac_lan_2024-07-09T15-39-17.944Z.log](https://github.com/user-attachments/files/16145673/home-assistant_midea_ac_lan_2024-07-09T15-39-17.944Z.log)

**Comment by chemelli74** [comment]
@invoker-karl, which mobile app are you using to control your devices ?
We need exact name (and maybe a screenshot of the icon just to be sure ).

**Comment by invoker-karl** [comment]
我通过“美的美居”移动应用程序来控制我的设备。 图标截图见下：
![e84cf0b535670b82d00b976b09feaff](https://github.com/wuwentao/midea_ac_lan/assets/32891226/3795857f-5cae-4c6e-a5a7-f0ea3bad614c)

**Comment by wuwentao** [comment]
thanks, still not fix, should check more and try different method.

**Comment by chemelli74** [comment]
@invoker-karl plase use the new SmartHome app:

![image](https://github.com/wuwentao/midea_ac_lan/assets/57354320/2ebcb516-ed93-4585-9cba-dc7a9920d69c)

To login there I had to delete my old Midea account and create a new one.
Then login worked and was able to use this integration.

**Comment by invoker-karl** [comment]
> 谢谢，仍然没有修复，应该检查更多并尝试不同的方法。

请问不能使用美的美居吗？  我刚刚试了下smart home，这个需要重新创建账号，且服务地区没有大陆的选项。

**Comment by chemelli74** [comment]
Mercury is not in the list of supported cloud

**Comment by rokam** [comment]
0.5.4 should fix your issue

**Comment by invoker-karl** [comment]
我已更新为0.5.4，当我使用“美的美居” APP，添加洗衣机仍然为Can't get available token for this device。

**Comment by wuwentao** [comment]
由于github当前存在大量同样duplicate的issue，因此先关闭当前issue，统一使用 https://github.com/wuwentao/midea_ac_lan/issues/275 来跟踪和处理，避免大量重复问题的跟踪和处理。
当然，当前issue仍然可以继续更新和发送其他消息
