### ISSUE TITLE
Midea AC Mobile 35C - losing connection (LAN) after removing access to internet.

### ISSUE THREAD

**Issue by NihilUnum** [wuwentao/midea_ac_lan#73]
Hi
I'm not sure if this is a bug or a misconfiguration on my part, but after a successful installation of the Midea AC LAN (including the fork from here), I lose access to the air conditioner when I block internet access. This means my setup isn't cloud-free, which I thought it should be. Am I doing something wrong? Or is this a code issue? Has anyone found a way to configure it to be permanently cloud-free?

**Comment by NihilUnum** [comment]
I'm not at home right now, but I remember that the Wi-Fi symbol was blinking slowly, and ping didn't respond either.

**Comment by chemelli74** [comment]
> I'm not at home right now, but I remember that the Wi-Fi symbol was blinking slowly, and ping didn't respond either.

This is a known behaviour of newer WI-FI dongles; look [here ](https://github.com/WMP/midea-ac-py/tree/support-8370?tab=readme-ov-file#install-fake-cloud-only-if-you-have-protocol-version-3)to make it fully local.

**Comment by NihilUnum** [comment]
Thanks for your quick response. 
I'll try it this evening. This forced cloud dependency is really frustrating...

**Comment by NihilUnum** [comment]
As per the instructions, I have set up the redirection on my OpenWRT router and tested it with nslookup, resulting in:

```
Server:  openwrt
Address:  192.168.11.254

Name:    module.appsmb.com
Address:  192.168.11.2
```

I downloaded the Python script and set it up as a service, resulting in:

```
$ sudo systemctl status fake-cloud
● fake-cloud.service - Fake Cloud Server for Midea AC
     Loaded: loaded (/etc/systemd/system/fake-cloud.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-06-09 15:07:06 CEST; 1 day 4h ago
   Main PID: 470 (python3)
      Tasks: 1 (limit: 8186)
     Memory: 9.8M
        CPU: 67ms
     CGroup: /system.slice/fake-cloud.service
             └─470 /usr/bin/python3 /usr/local/sbin/fake-cloud-wmp.py
```
Actually pretty simple but unfortunately my midea became unavailable.
Any Ideas?

**Comment by NihilUnum** [comment]
Hmm looks like this script does not work with my Midea AC. 
It is connected:
sudo netstat -anp | grep :443
tcp        0      0 192.168.11.2:443        0.0.0.0:*               LISTEN      9826/python3
tcp       13      0 192.168.11.2:443        192.168.11.229:40003    VERBUNDEN   9826/python3
But couple minutes later its unavailable.
