### ISSUE TITLE
C3 heat pump - how to activate “super_silent" mode ?

### ISSUE THREAD

**Issue by erikgieseler** [wuwentao/midea_ac_lan#80]
### HA core version

2024.6.1

### Integration version

0.4.1

### Device type and model

Heat Pump Wi-Fi Controller 171H120F

### Used App

SmartHome

### The description of problem

Hello, 

in the source code of the C3 heat pump there are the modes “silent_mode” and “super_silent”. 

There is a switch in the HA for “silent_mode”.
But there is nothing like this for “super_silent”.

Does anyone know how to activate the “super_silent” mode ?

References:
https://github.com/georgezhao2010/midea_ac_lan/issues/339
https://github.com/georgezhao2010/midea_ac_lan/commit/448410e86b5b33af9adcf690a02c8dd6e267283e

**Comment by wuwentao** [comment]
@erikgieseler 
there is no silent_level or super_silent option for it.
and you may need to find out the super_silent data diff like origin issue

and maybe you can follow the same step, to get the data diff like below

```
16:41:10 - silent mode is turned on
16:43:10 - silent mode is turned off

message "body" difference:
"010017a00303201e27c037191912371919053c223c14260000" - turned off
"010017a20303201e27c037191912371919053c223c14260000" - turned on
```

seems it only have  on and off, no silent_level or super_silent data provide, so georgezhao2010 didn't finish it, just defined this args, but you can't use it.

**Comment by erikgieseler** [comment]
I have tested this accordingly, unfortunately there are no differences in the data between silent and super_silent when I activate this in the app.

But I found out by trial and error that you can activate the super_silent mode by sending 0x03 instead of 0x01 as with silent.

The example code would then look like this:

```
class MessageSetSuperSilent(MessageC3Base):
    def __init__(self, protocol_version):
        super().__init__(
            protocol_version=protocol_version,
            message_type=MessageType.set,
            body_type=0x05)
        self.super_silent_mode = False

    @property
    def _body(self):
        super_silent_mode = 0x03 if self.super_silent_mode else 0

        return bytearray([
            super_silent_mode,
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00
        ])
```
You could perhaps just add a pushbutton to activate the super_silent mode.
Unfortunately, only silent mode would then be displayed as active.

Unfortunately my programming skills are not that good, otherwise I would program it myself :-(

silent on:
![silent](https://github.com/wuwentao/midea_ac_lan/assets/72557610/f8dfc48f-d8e2-4fbc-8402-8d60fe619e18)

super_silent on:
![super_silent](https://github.com/wuwentao/midea_ac_lan/assets/72557610/26a7892b-a7cc-4dfc-8fff-adc44455d570)

off:
![off](https://github.com/wuwentao/midea_ac_lan/assets/72557610/4177021d-b142-45f5-a5d8-ba206b44b706)

**Comment by erikgieseler** [comment]
I found source code in another GitHub repository that seems to have been extracted from the SmartHome app. 
Maybe that will help.

Source:
https://github.com/mill1000/midea-msmart/issues/107

[T0xC3_2023120100_sm.zip](https://github.com/user-attachments/files/15846679/T0xC3_2023120100_sm.zip)
[T_0000_C3_171H120F_2023062601.txt](https://github.com/user-attachments/files/15846683/T_0000_C3_171H120F_2023062601.txt)

**Comment by rokam** [comment]
@erikgieseler ok,  you've found how to set super_silent, now we need the bit that represents super_silent in the query message.
Can you please send a log with the received message?

**Comment by rokam** [comment]
PR open on the lib side: https://github.com/rokam/midea-local/pull/210

I still need that message to check if the status is retrieved by the correct bit

**Comment by rokam** [comment]
Also, try setting supersilent with body 050200.... instead of 050300...

**Comment by erikgieseler** [comment]
Today I installed version 0.5.5 which should contain the new silence option from midea-local.
What do I have to do to test this? 
Is a log where I switch through all silence levels with the app sufficient? 
If yes, then this is attached.
[_homeassistant_logs.txt](https://github.com/user-attachments/files/16531260/_homeassistant_logs.txt)

**Comment by rokam** [comment]
Thanks. I found an issue with the lib. https://github.com/rokam/midea-local/pull/265

**Comment by erikgieseler** [comment]
Here is a log of lib version 2.6.2 with the modes on, level 1, level 2 and off.
[_homeassistant_logs.txt](https://github.com/user-attachments/files/16569731/_homeassistant_logs.txt)

**Comment by rokam** [comment]
It looks good

**Comment by erikgieseler** [comment]
The selection of silent mode now works without any problems. 
Thank you very much!
