### ISSUE TITLE
希望能支持配置翻译字典

### ISSUE THREAD

**Issue by yyax** [wuwentao/midea_ac_lan#98]
### 设备类型及型号 (或SN)

Front Load Washer 38124878

### 新功能的描述

好多设备的状态不是我想要的语言，等待homeassistant官方支持又遥遥无期，所以希望midea ac lan能支持配置翻译字典，就像mito那样的，谢谢啦！https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/core/translation_languages.py

**Comment by Necroneco** [comment]
翻译会完善的，我正准备开始这块，不过估计会先按HA官方方案来一遍。

**Comment by yyax** [comment]
希望加快进程，辛苦了

**Comment by wuwentao** [comment]
@yyax 这个功能应该是根据设备具体类型来天津的，应该 @Necroneco 已经解决了，但是不同的设备可能需要分别添加多种翻译语言，工作量会比较大。
你的设备是滚筒洗衣机么？ 也就是0xDB?

**Comment by yyax** [comment]
> @yyax这个功能应该是根据设备具体类型来添加的，应该@Necroneco已经解决了，但是不同的设备可能需要分别添加翻译多种语言，工作量会比较大。一次不能把所有设备都加完，只能有需求了，逐个设备添加吧。 你的设备是货架洗衣机嗯？0xDB？

设备有滚筒洗衣机，洗碗机，微蒸烤，热水器......

**Comment by yyax** [comment]
> 有点多，哈哈，但是现在设备尴尬的问题不是技术问题，也不是需要翻译的设备量多大，而是：翻译成什么中文合适…… 英文的基本不需要翻译，但是中文换成什么名词，和你app里面的匹配或者显示一致，就无法明确，如果没有这个条件的话，应该不确定怎么翻译。
> 
> 以前希望官方的lua脚本带有完整的中文注释和说明，直接对注释修改就完事了，现在我看过新版本，已经没有注释了。
> 
> 实在不行，就只能用最笨的办法去干体力活了：借你账号登录美居，临时改密码，直接登录你账号，一个看实际的中文名字，尝试人工翻译一下关机的字段即可。
> 
> 我先抽空寻找是否有旧的带中文注释的lua脚本吧

如果逐个翻译的话确实是个体力活，所以我希望能够外挂字典来翻译就像miot集成那样的。比如洗衣机和洗碗机的状态都有Idle，如果能够外挂Idle=空闲（也可以是其他语言），那么就一下解决了多个设备的空闲状态，我不懂技术，只是说出自己的想法，感谢回复

**Comment by Necroneco** [comment]
> 如果逐个翻译的话确实是个体力活，所以我希望能够外挂字典来翻译就像miot集成那样的。比如洗衣机和洗碗机的状态都有Idle，如果能够外挂Idle=空闲（也可以是其他语言），那么就一下解决了多个设备的空闲状态，我不懂技术，只是说出自己的想法，感谢回复

现在就是这么干的，就是说 即使这么干 它也是个体力活。
然后就像上面说的，没有设备的话 不太清楚用什么词来翻译比较好，所以还是希望有设备的用户可以来贡献一下翻译。

我等下会把所有设备的翻译字段都整理到 `translations/{language}.json` 中，方便贡献翻译。

**Comment by Necroneco** [comment]
@yyax 可以看一下PR #294 ，等合并之后，你可以通过 `translations/zh-Hans.json` 来贡献翻译。不确定的 key 可以在 `midea_devices.py` 中查阅。
